-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_linear_ap_fixed_16_6_5_3_0_ap_fixed_16_7_4_0_0_linear_config10_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of inference_linear_ap_fixed_16_6_5_3_0_ap_fixed_16_7_4_0_0_linear_config10_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal p_Val2_s_fu_92_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_fu_106_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_11_fu_88_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_fu_120_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_fu_102_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_7_fu_130_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_7_fu_144_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_10_fu_84_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_7_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_7_fu_158_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_7_fu_140_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_8_fu_168_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_8_fu_182_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_9_fu_80_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_8_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_8_fu_196_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_8_fu_178_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_9_fu_206_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_9_fu_220_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_8_fu_76_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_9_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_9_fu_234_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_9_fu_216_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_10_fu_244_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_10_fu_258_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_7_fu_72_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_10_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_10_fu_272_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_10_fu_254_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_11_fu_282_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_11_fu_296_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_fu_68_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_11_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_11_fu_310_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_11_fu_292_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_fu_124_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_7_fu_162_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_8_fu_200_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_9_fu_238_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_10_fu_276_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_11_fu_314_p2 : STD_LOGIC_VECTOR (15 downto 0);


begin



    add_ln377_10_fu_276_p2 <= std_logic_vector(unsigned(zext_ln377_10_fu_272_p1) + unsigned(sext_ln818_10_fu_254_p1));
    add_ln377_11_fu_314_p2 <= std_logic_vector(unsigned(zext_ln377_11_fu_310_p1) + unsigned(sext_ln818_11_fu_292_p1));
    add_ln377_7_fu_162_p2 <= std_logic_vector(unsigned(zext_ln377_7_fu_158_p1) + unsigned(sext_ln818_7_fu_140_p1));
    add_ln377_8_fu_200_p2 <= std_logic_vector(unsigned(zext_ln377_8_fu_196_p1) + unsigned(sext_ln818_8_fu_178_p1));
    add_ln377_9_fu_238_p2 <= std_logic_vector(unsigned(zext_ln377_9_fu_234_p1) + unsigned(sext_ln818_9_fu_216_p1));
    add_ln377_fu_124_p2 <= std_logic_vector(unsigned(zext_ln377_fu_120_p1) + unsigned(sext_ln818_fu_102_p1));
    and_ln374_10_fu_266_p2 <= (trunc_ln29_7_fu_72_p1 and tmp_10_fu_258_p3);
    and_ln374_11_fu_304_p2 <= (trunc_ln29_fu_68_p1 and tmp_11_fu_296_p3);
    and_ln374_7_fu_152_p2 <= (trunc_ln29_10_fu_84_p1 and tmp_7_fu_144_p3);
    and_ln374_8_fu_190_p2 <= (trunc_ln29_9_fu_80_p1 and tmp_8_fu_182_p3);
    and_ln374_9_fu_228_p2 <= (trunc_ln29_8_fu_76_p1 and tmp_9_fu_220_p3);
    and_ln374_fu_114_p2 <= (trunc_ln29_11_fu_88_p1 and tmp_fu_106_p3);
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln377_fu_124_p2;
    ap_return_1 <= add_ln377_7_fu_162_p2;
    ap_return_2 <= add_ln377_8_fu_200_p2;
    ap_return_3 <= add_ln377_9_fu_238_p2;
    ap_return_4 <= add_ln377_10_fu_276_p2;
    ap_return_5 <= add_ln377_11_fu_314_p2;
    p_Val2_10_fu_244_p4 <= p_read6(15 downto 1);
    p_Val2_11_fu_282_p4 <= p_read9(15 downto 1);
    p_Val2_7_fu_130_p4 <= p_read2(15 downto 1);
    p_Val2_8_fu_168_p4 <= p_read3(15 downto 1);
    p_Val2_9_fu_206_p4 <= p_read4(15 downto 1);
    p_Val2_s_fu_92_p4 <= p_read(15 downto 1);
        sext_ln818_10_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_10_fu_244_p4),16));

        sext_ln818_11_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_11_fu_282_p4),16));

        sext_ln818_7_fu_140_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_7_fu_130_p4),16));

        sext_ln818_8_fu_178_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_8_fu_168_p4),16));

        sext_ln818_9_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_9_fu_206_p4),16));

        sext_ln818_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_s_fu_92_p4),16));

    tmp_10_fu_258_p3 <= p_read6(1 downto 1);
    tmp_11_fu_296_p3 <= p_read9(1 downto 1);
    tmp_7_fu_144_p3 <= p_read2(1 downto 1);
    tmp_8_fu_182_p3 <= p_read3(1 downto 1);
    tmp_9_fu_220_p3 <= p_read4(1 downto 1);
    tmp_fu_106_p3 <= p_read(1 downto 1);
    trunc_ln29_10_fu_84_p1 <= p_read2(1 - 1 downto 0);
    trunc_ln29_11_fu_88_p1 <= p_read(1 - 1 downto 0);
    trunc_ln29_7_fu_72_p1 <= p_read6(1 - 1 downto 0);
    trunc_ln29_8_fu_76_p1 <= p_read4(1 - 1 downto 0);
    trunc_ln29_9_fu_80_p1 <= p_read3(1 - 1 downto 0);
    trunc_ln29_fu_68_p1 <= p_read9(1 - 1 downto 0);
    zext_ln377_10_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_10_fu_266_p2),16));
    zext_ln377_11_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_11_fu_304_p2),16));
    zext_ln377_7_fu_158_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_7_fu_152_p2),16));
    zext_ln377_8_fu_196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_8_fu_190_p2),16));
    zext_ln377_9_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_9_fu_228_p2),16));
    zext_ln377_fu_120_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_fu_114_p2),16));
end behav;
