-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config11_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config11_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal trunc_ln_fu_84_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln_fu_98_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_fu_106_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_14_fu_130_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1273_fu_138_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_s_fu_122_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_21_fu_142_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_15_fu_158_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_22_fu_166_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_17_fu_190_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1273_16_fu_198_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_16_fu_182_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_23_fu_202_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1270_fu_218_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_shl_fu_222_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_fu_218_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl_fu_222_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln1270_fu_230_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln818_27_fu_148_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_28_fu_172_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_fu_246_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_s_fu_112_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_30_fu_236_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_fu_94_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_47_fu_258_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_29_fu_208_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_48_fu_264_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_46_fu_252_p2 : STD_LOGIC_VECTOR (15 downto 0);


begin



    add_ln813_46_fu_252_p2 <= std_logic_vector(unsigned(add_ln813_fu_246_p2) + unsigned(trunc_ln818_s_fu_112_p4));
    add_ln813_47_fu_258_p2 <= std_logic_vector(unsigned(trunc_ln818_30_fu_236_p4) + unsigned(sext_ln818_fu_94_p1));
    add_ln813_48_fu_264_p2 <= std_logic_vector(unsigned(add_ln813_47_fu_258_p2) + unsigned(trunc_ln818_29_fu_208_p4));
    add_ln813_fu_246_p2 <= std_logic_vector(unsigned(trunc_ln818_27_fu_148_p4) + unsigned(trunc_ln818_28_fu_172_p4));
    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(add_ln813_48_fu_264_p2) + unsigned(add_ln813_46_fu_252_p2));
    p_shl_fu_222_p1 <= p_read9;
    p_shl_fu_222_p3 <= (p_shl_fu_222_p1 & ap_const_lv3_0);
    r_V_21_fu_142_p2 <= std_logic_vector(signed(sext_ln1273_fu_138_p1) - signed(shl_ln1273_s_fu_122_p3));
    r_V_22_fu_166_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(shl_ln1273_15_fu_158_p3));
    r_V_23_fu_202_p2 <= std_logic_vector(signed(sext_ln1273_16_fu_198_p1) - signed(shl_ln1273_16_fu_182_p3));
    r_V_fu_106_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(shl_ln_fu_98_p3));
    sext_ln1270_fu_218_p0 <= p_read9;
        sext_ln1270_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1270_fu_218_p0),19));

        sext_ln1273_16_fu_198_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_17_fu_190_p3),19));

        sext_ln1273_fu_138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_14_fu_130_p3),19));

        sext_ln818_fu_94_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_84_p4),16));

    shl_ln1273_14_fu_130_p3 <= (p_read3 & ap_const_lv1_0);
    shl_ln1273_15_fu_158_p3 <= (p_read4 & ap_const_lv3_0);
    shl_ln1273_16_fu_182_p3 <= (p_read6 & ap_const_lv3_0);
    shl_ln1273_17_fu_190_p3 <= (p_read6 & ap_const_lv1_0);
    shl_ln1273_s_fu_122_p3 <= (p_read3 & ap_const_lv3_0);
    shl_ln_fu_98_p3 <= (p_read2 & ap_const_lv3_0);
    sub_ln1270_fu_230_p2 <= std_logic_vector(signed(sext_ln1270_fu_218_p1) - signed(p_shl_fu_222_p3));
    trunc_ln818_27_fu_148_p4 <= r_V_21_fu_142_p2(18 downto 3);
    trunc_ln818_28_fu_172_p4 <= r_V_22_fu_166_p2(18 downto 3);
    trunc_ln818_29_fu_208_p4 <= r_V_23_fu_202_p2(18 downto 3);
    trunc_ln818_30_fu_236_p4 <= sub_ln1270_fu_230_p2(18 downto 3);
    trunc_ln818_s_fu_112_p4 <= r_V_fu_106_p2(18 downto 3);
    trunc_ln_fu_84_p4 <= p_read(15 downto 1);
end behav;
