-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_linear_ap_fixed_8_2_5_3_0_ap_fixed_16_6_5_3_0_linear_config3_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of inference_linear_ap_fixed_8_2_5_3_0_ap_fixed_16_6_5_3_0_linear_config3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal shl_ln_fu_56_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln838_1_fu_68_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln838_2_fu_80_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln838_3_fu_92_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln838_4_fu_104_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln837_fu_64_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln837_1_fu_76_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln837_2_fu_88_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln837_3_fu_100_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln34_fu_112_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= sext_ln837_fu_64_p1;
    ap_return_1 <= sext_ln837_1_fu_76_p1;
    ap_return_2 <= sext_ln837_2_fu_88_p1;
    ap_return_3 <= sext_ln837_3_fu_100_p1;
    ap_return_4 <= sext_ln34_fu_112_p1;
        sext_ln34_fu_112_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln838_4_fu_104_p3),16));

        sext_ln837_1_fu_76_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln838_1_fu_68_p3),16));

        sext_ln837_2_fu_88_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln838_2_fu_80_p3),16));

        sext_ln837_3_fu_100_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln838_3_fu_92_p3),16));

        sext_ln837_fu_64_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_56_p3),16));

    shl_ln838_1_fu_68_p3 <= (p_read1 & ap_const_lv4_0);
    shl_ln838_2_fu_80_p3 <= (p_read2 & ap_const_lv4_0);
    shl_ln838_3_fu_92_p3 <= (p_read3 & ap_const_lv4_0);
    shl_ln838_4_fu_104_p3 <= (p_read4 & ap_const_lv4_0);
    shl_ln_fu_56_p3 <= (p_read & ap_const_lv4_0);
end behav;
