-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config8_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config8_s is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv19_B : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000001011";
    constant ap_const_lv19_7FFF5 : STD_LOGIC_VECTOR (18 downto 0) := "1111111111111110101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal p_read512_reg_1484 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_read411_reg_1489 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read310_reg_1497 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read29_reg_1504 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read18_reg_1512 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_16_reg_1520 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_21_reg_1529 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_25_reg_1534 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_23_fu_887_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_23_reg_1539 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_28_fu_893_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_28_reg_1544 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_34_fu_905_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_34_reg_1549 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_44_fu_917_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_44_reg_1554 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1270_fu_149_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_fu_923_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln1270_fu_149_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln1270_1_fu_152_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_1_fu_1050_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln1270_1_fu_152_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln818_8_fu_631_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_8_fu_631_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln818_s_fu_645_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_s_fu_645_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln1273_10_fu_659_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_7_fu_663_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_7_fu_663_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1273_11_fu_671_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_17_fu_675_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1273_10_fu_659_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_14_fu_681_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_10_fu_697_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_10_fu_697_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1273_13_fu_709_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal r_V_15_fu_713_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln818_19_fu_719_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal r_V_16_fu_733_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_11_fu_759_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_11_fu_759_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln1273_15_fu_767_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1273_12_fu_705_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_18_fu_773_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1273_14_fu_789_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_12_fu_793_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_12_fu_793_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1273_15_fu_801_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1273_14_fu_789_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_19_fu_805_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_13_fu_821_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_13_fu_821_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln1273_17_fu_829_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_20_fu_835_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln818_25_fu_851_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_26_fu_861_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_26_fu_861_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln818_18_fu_687_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_23_fu_811_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_2_fu_655_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_fu_641_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_22_fu_881_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_21_fu_875_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_13_fu_729_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_24_fu_841_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_33_fu_899_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_20_fu_739_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_5_fu_871_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_43_fu_911_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_22_fu_779_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_927_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1273_fu_934_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_fu_938_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_1_fu_954_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln1273_fu_961_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_1_fu_967_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_2_fu_983_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1273_1_fu_990_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_2_fu_994_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln1270_fu_149_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_3_fu_1023_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1273_2_fu_1030_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln818_12_fu_1020_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_3_fu_1034_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_5_fu_1061_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln1273_4_fu_1054_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln1273_3_fu_1072_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1273_3_fu_1068_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_4_fu_1078_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_6_fu_1094_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1273_4_fu_1101_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_5_fu_1105_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln1270_1_fu_152_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1273_5_fu_1131_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl3_fu_1134_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln1270_fu_1141_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_6_fu_1157_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_fu_1173_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1273_6_fu_1180_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_7_fu_1184_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_8_fu_1200_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_8_fu_1219_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_9_fu_1226_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_9_fu_1242_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1273_8_fu_1249_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln1273_7_fu_1216_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_10_fu_1253_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln1273_s_fu_1269_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1273_9_fu_1276_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_11_fu_1280_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_12_fu_1296_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_13_fu_1312_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal trunc_ln818_17_fu_1318_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_fu_1331_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_9_fu_1040_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_4_fu_1147_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_13_fu_1232_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_19_fu_1342_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_fu_944_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_20_fu_1348_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_1_fu_1084_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_25_fu_1359_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_10_fu_1163_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_14_fu_1259_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_27_fu_1369_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_29_fu_1375_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_26_fu_1364_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_2_fu_1111_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_15_fu_1286_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_31_fu_1386_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_5_fu_973_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_32_fu_1392_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_6_fu_1000_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_11_fu_1190_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_36_fu_1403_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_3_fu_1121_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_4_fu_1328_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_38_fu_1415_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_16_fu_1302_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_39_fu_1420_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_37_fu_1409_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_12_fu_1206_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_41_fu_1432_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_7_fu_1010_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_42_fu_1437_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_24_fu_1354_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_30_fu_1380_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_35_fu_1398_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_40_fu_1426_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_45_fu_1443_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_18_fu_1336_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component inference_mul_16s_5ns_19_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component inference_mul_16s_5s_19_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;



begin
    mul_16s_5ns_19_1_1_U784 : component inference_mul_16s_5ns_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 5,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln1270_fu_149_p0,
        din1 => mul_ln1270_fu_149_p1,
        dout => mul_ln1270_fu_149_p2);

    mul_16s_5s_19_1_1_U785 : component inference_mul_16s_5s_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 5,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln1270_1_fu_152_p0,
        din1 => mul_ln1270_1_fu_152_p1,
        dout => mul_ln1270_1_fu_152_p2);




    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln813_23_reg_1539 <= add_ln813_23_fu_887_p2;
                add_ln813_28_reg_1544 <= add_ln813_28_fu_893_p2;
                add_ln813_34_reg_1549 <= add_ln813_34_fu_905_p2;
                add_ln813_44_reg_1554 <= add_ln813_44_fu_917_p2;
                p_read18_reg_1512 <= p_read1;
                p_read29_reg_1504 <= p_read2;
                p_read310_reg_1497 <= p_read3;
                p_read411_reg_1489 <= p_read4;
                p_read512_reg_1484 <= p_read5;
                p_read_16_reg_1520 <= p_read;
                trunc_ln818_21_reg_1529 <= r_V_17_fu_675_p2(18 downto 3);
                trunc_ln818_25_reg_1534 <= trunc_ln818_25_fu_851_p1(15 downto 2);
            end if;
        end if;
    end process;
    add_ln813_18_fu_1336_p2 <= std_logic_vector(unsigned(add_ln813_fu_1331_p2) + unsigned(trunc_ln818_9_fu_1040_p4));
    add_ln813_19_fu_1342_p2 <= std_logic_vector(unsigned(trunc_ln818_4_fu_1147_p4) + unsigned(trunc_ln818_13_fu_1232_p4));
    add_ln813_20_fu_1348_p2 <= std_logic_vector(unsigned(add_ln813_19_fu_1342_p2) + unsigned(trunc_ln_fu_944_p4));
    add_ln813_21_fu_875_p2 <= std_logic_vector(unsigned(trunc_ln818_18_fu_687_p4) + unsigned(trunc_ln818_23_fu_811_p4));
    add_ln813_22_fu_881_p2 <= std_logic_vector(signed(sext_ln818_2_fu_655_p1) + signed(sext_ln818_fu_641_p1));
    add_ln813_23_fu_887_p2 <= std_logic_vector(unsigned(add_ln813_22_fu_881_p2) + unsigned(add_ln813_21_fu_875_p2));
    add_ln813_24_fu_1354_p2 <= std_logic_vector(unsigned(add_ln813_23_reg_1539) + unsigned(add_ln813_20_fu_1348_p2));
    add_ln813_25_fu_1359_p2 <= std_logic_vector(unsigned(trunc_ln818_1_fu_1084_p4) + unsigned(p_read_16_reg_1520));
    add_ln813_26_fu_1364_p2 <= std_logic_vector(unsigned(add_ln813_25_fu_1359_p2) + unsigned(p_read18_reg_1512));
    add_ln813_27_fu_1369_p2 <= std_logic_vector(unsigned(trunc_ln818_10_fu_1163_p4) + unsigned(trunc_ln818_14_fu_1259_p4));
    add_ln813_28_fu_893_p2 <= std_logic_vector(signed(sext_ln818_13_fu_729_p1) + signed(trunc_ln818_24_fu_841_p4));
    add_ln813_29_fu_1375_p2 <= std_logic_vector(unsigned(add_ln813_28_reg_1544) + unsigned(add_ln813_27_fu_1369_p2));
    add_ln813_30_fu_1380_p2 <= std_logic_vector(unsigned(add_ln813_29_fu_1375_p2) + unsigned(add_ln813_26_fu_1364_p2));
    add_ln813_31_fu_1386_p2 <= std_logic_vector(unsigned(trunc_ln818_2_fu_1111_p4) + unsigned(trunc_ln818_15_fu_1286_p4));
    add_ln813_32_fu_1392_p2 <= std_logic_vector(unsigned(add_ln813_31_fu_1386_p2) + unsigned(trunc_ln818_5_fu_973_p4));
    add_ln813_33_fu_899_p2 <= std_logic_vector(unsigned(trunc_ln818_23_fu_811_p4) + unsigned(sext_ln818_fu_641_p1));
    add_ln813_34_fu_905_p2 <= std_logic_vector(unsigned(add_ln813_33_fu_899_p2) + unsigned(trunc_ln818_20_fu_739_p4));
    add_ln813_35_fu_1398_p2 <= std_logic_vector(unsigned(add_ln813_34_reg_1549) + unsigned(add_ln813_32_fu_1392_p2));
    add_ln813_36_fu_1403_p2 <= std_logic_vector(unsigned(trunc_ln818_6_fu_1000_p4) + unsigned(trunc_ln818_11_fu_1190_p4));
    add_ln813_37_fu_1409_p2 <= std_logic_vector(unsigned(add_ln813_36_fu_1403_p2) + unsigned(trunc_ln818_3_fu_1121_p4));
    add_ln813_38_fu_1415_p2 <= std_logic_vector(unsigned(trunc_ln818_21_reg_1529) + unsigned(sext_ln818_4_fu_1328_p1));
    add_ln813_39_fu_1420_p2 <= std_logic_vector(unsigned(add_ln813_38_fu_1415_p2) + unsigned(trunc_ln818_16_fu_1302_p4));
    add_ln813_40_fu_1426_p2 <= std_logic_vector(unsigned(add_ln813_39_fu_1420_p2) + unsigned(add_ln813_37_fu_1409_p2));
    add_ln813_41_fu_1432_p2 <= std_logic_vector(unsigned(trunc_ln818_12_fu_1206_p4) + unsigned(p_read18_reg_1512));
    add_ln813_42_fu_1437_p2 <= std_logic_vector(unsigned(add_ln813_41_fu_1432_p2) + unsigned(trunc_ln818_7_fu_1010_p4));
    add_ln813_43_fu_911_p2 <= std_logic_vector(signed(sext_ln818_2_fu_655_p1) + signed(sext_ln818_5_fu_871_p1));
    add_ln813_44_fu_917_p2 <= std_logic_vector(unsigned(add_ln813_43_fu_911_p2) + unsigned(trunc_ln818_22_fu_779_p4));
    add_ln813_45_fu_1443_p2 <= std_logic_vector(unsigned(add_ln813_44_reg_1554) + unsigned(add_ln813_42_fu_1437_p2));
    add_ln813_fu_1331_p2 <= std_logic_vector(unsigned(trunc_ln818_17_fu_1318_p4) + unsigned(p_read512_reg_1484));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return_0 <= add_ln813_24_fu_1354_p2;
    ap_return_1 <= add_ln813_30_fu_1380_p2;
    ap_return_2 <= add_ln813_35_fu_1398_p2;
    ap_return_3 <= add_ln813_40_fu_1426_p2;
    ap_return_4 <= add_ln813_45_fu_1443_p2;
    ap_return_5 <= add_ln813_18_fu_1336_p2;
    mul_ln1270_1_fu_152_p0 <= sext_ln1270_1_fu_1050_p1(16 - 1 downto 0);
    mul_ln1270_1_fu_152_p1 <= ap_const_lv19_7FFF5(5 - 1 downto 0);
    mul_ln1270_fu_149_p0 <= sext_ln1270_fu_923_p1(16 - 1 downto 0);
    mul_ln1270_fu_149_p1 <= ap_const_lv19_B(5 - 1 downto 0);
    p_shl3_fu_1134_p3 <= (p_read310_reg_1497 & ap_const_lv3_0);
    r_V_10_fu_1253_p2 <= std_logic_vector(signed(sext_ln1273_8_fu_1249_p1) - signed(sext_ln1273_7_fu_1216_p1));
    r_V_11_fu_1280_p2 <= std_logic_vector(signed(sext_ln1273_9_fu_1276_p1) - signed(shl_ln1273_8_fu_1219_p3));
    r_V_12_fu_1296_p2 <= std_logic_vector(signed(sext_ln1273_7_fu_1216_p1) - signed(sext_ln1273_8_fu_1249_p1));
    r_V_13_fu_1312_p2 <= std_logic_vector(unsigned(r_V_9_fu_1226_p2) - unsigned(sext_ln1273_7_fu_1216_p1));
    r_V_14_fu_681_p2 <= std_logic_vector(unsigned(r_V_17_fu_675_p2) - unsigned(sext_ln1273_10_fu_659_p1));
    r_V_15_fu_713_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(sext_ln1273_13_fu_709_p1));
    r_V_16_fu_733_p2 <= std_logic_vector(signed(sext_ln1273_11_fu_671_p1) - signed(sext_ln1273_10_fu_659_p1));
    r_V_17_fu_675_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(sext_ln1273_11_fu_671_p1));
    r_V_18_fu_773_p2 <= std_logic_vector(unsigned(sub_ln1273_15_fu_767_p2) - unsigned(sext_ln1273_12_fu_705_p1));
    r_V_19_fu_805_p2 <= std_logic_vector(signed(sext_ln1273_15_fu_801_p1) + signed(sext_ln1273_14_fu_789_p1));
    r_V_1_fu_967_p2 <= std_logic_vector(unsigned(sub_ln1273_fu_961_p2) - unsigned(sext_ln1270_fu_923_p1));
    r_V_20_fu_835_p2 <= std_logic_vector(unsigned(sub_ln1273_17_fu_829_p2) - unsigned(sext_ln1273_14_fu_789_p1));
    r_V_2_fu_994_p2 <= std_logic_vector(unsigned(shl_ln1273_1_fu_954_p3) + unsigned(sext_ln1273_1_fu_990_p1));
    r_V_3_fu_1034_p2 <= std_logic_vector(signed(sext_ln1273_2_fu_1030_p1) - signed(sext_ln818_12_fu_1020_p1));
    r_V_4_fu_1078_p2 <= std_logic_vector(unsigned(sub_ln1273_3_fu_1072_p2) - unsigned(sext_ln1273_3_fu_1068_p1));
    r_V_5_fu_1105_p2 <= std_logic_vector(signed(sext_ln1273_4_fu_1101_p1) - signed(sext_ln1270_1_fu_1050_p1));
    r_V_6_fu_1157_p2 <= std_logic_vector(unsigned(p_shl3_fu_1134_p3) + unsigned(sext_ln1273_5_fu_1131_p1));
    r_V_7_fu_1184_p2 <= std_logic_vector(signed(sext_ln1273_5_fu_1131_p1) - signed(sext_ln1273_6_fu_1180_p1));
    r_V_8_fu_1200_p2 <= std_logic_vector(unsigned(p_shl3_fu_1134_p3) - unsigned(sext_ln1273_5_fu_1131_p1));
    r_V_9_fu_1226_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(shl_ln1273_8_fu_1219_p3));
    r_V_fu_938_p2 <= std_logic_vector(signed(sext_ln1273_fu_934_p1) + signed(sext_ln1270_fu_923_p1));
        sext_ln1270_1_fu_1050_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read29_reg_1504),19));

        sext_ln1270_fu_923_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_16_reg_1520),19));

    sext_ln1273_10_fu_659_p0 <= p_read5;
        sext_ln1273_10_fu_659_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_10_fu_659_p0),19));

        sext_ln1273_11_fu_671_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_7_fu_663_p3),19));

        sext_ln1273_12_fu_705_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_10_fu_697_p3),19));

        sext_ln1273_13_fu_709_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_10_fu_697_p3),18));

    sext_ln1273_14_fu_789_p0 <= p_read6;
        sext_ln1273_14_fu_789_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1273_14_fu_789_p0),19));

        sext_ln1273_15_fu_801_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_12_fu_793_p3),19));

        sext_ln1273_1_fu_990_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_2_fu_983_p3),19));

        sext_ln1273_2_fu_1030_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_3_fu_1023_p3),19));

        sext_ln1273_3_fu_1068_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_5_fu_1061_p3),19));

        sext_ln1273_4_fu_1101_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_6_fu_1094_p3),19));

        sext_ln1273_5_fu_1131_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read310_reg_1497),19));

        sext_ln1273_6_fu_1180_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_1173_p3),19));

        sext_ln1273_7_fu_1216_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read411_reg_1489),19));

        sext_ln1273_8_fu_1249_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_9_fu_1242_p3),19));

        sext_ln1273_9_fu_1276_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_s_fu_1269_p3),19));

        sext_ln1273_fu_934_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_927_p3),19));

        sext_ln818_12_fu_1020_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read18_reg_1512),19));

        sext_ln818_13_fu_729_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_19_fu_719_p4),16));

        sext_ln818_2_fu_655_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_s_fu_645_p4),16));

        sext_ln818_4_fu_1328_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_25_reg_1534),16));

        sext_ln818_5_fu_871_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_26_fu_861_p4),16));

        sext_ln818_fu_641_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_8_fu_631_p4),16));

    shl_ln1273_10_fu_697_p1 <= p_read5;
    shl_ln1273_10_fu_697_p3 <= (shl_ln1273_10_fu_697_p1 & ap_const_lv1_0);
    shl_ln1273_11_fu_759_p1 <= p_read5;
    shl_ln1273_11_fu_759_p3 <= (shl_ln1273_11_fu_759_p1 & ap_const_lv3_0);
    shl_ln1273_12_fu_793_p1 <= p_read6;
    shl_ln1273_12_fu_793_p3 <= (shl_ln1273_12_fu_793_p1 & ap_const_lv2_0);
    shl_ln1273_13_fu_821_p1 <= p_read6;
    shl_ln1273_13_fu_821_p3 <= (shl_ln1273_13_fu_821_p1 & ap_const_lv3_0);
    shl_ln1273_1_fu_954_p3 <= (p_read_16_reg_1520 & ap_const_lv3_0);
    shl_ln1273_2_fu_983_p3 <= (p_read_16_reg_1520 & ap_const_lv1_0);
    shl_ln1273_3_fu_1023_p3 <= (p_read18_reg_1512 & ap_const_lv2_0);
    shl_ln1273_4_fu_1054_p3 <= (p_read29_reg_1504 & ap_const_lv3_0);
    shl_ln1273_5_fu_1061_p3 <= (p_read29_reg_1504 & ap_const_lv1_0);
    shl_ln1273_6_fu_1094_p3 <= (p_read29_reg_1504 & ap_const_lv2_0);
    shl_ln1273_7_fu_663_p1 <= p_read5;
    shl_ln1273_7_fu_663_p3 <= (shl_ln1273_7_fu_663_p1 & ap_const_lv2_0);
    shl_ln1273_8_fu_1219_p3 <= (p_read411_reg_1489 & ap_const_lv3_0);
    shl_ln1273_9_fu_1242_p3 <= (p_read411_reg_1489 & ap_const_lv2_0);
    shl_ln1273_s_fu_1269_p3 <= (p_read411_reg_1489 & ap_const_lv1_0);
    shl_ln_fu_927_p3 <= (p_read_16_reg_1520 & ap_const_lv2_0);
    sub_ln1270_fu_1141_p2 <= std_logic_vector(signed(sext_ln1273_5_fu_1131_p1) - signed(p_shl3_fu_1134_p3));
    sub_ln1273_15_fu_767_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(shl_ln1273_11_fu_759_p3));
    sub_ln1273_17_fu_829_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(shl_ln1273_13_fu_821_p3));
    sub_ln1273_3_fu_1072_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(shl_ln1273_4_fu_1054_p3));
    sub_ln1273_fu_961_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(shl_ln1273_1_fu_954_p3));
    tmp_fu_1173_p3 <= (p_read310_reg_1497 & ap_const_lv2_0);
    trunc_ln818_10_fu_1163_p4 <= r_V_6_fu_1157_p2(18 downto 3);
    trunc_ln818_11_fu_1190_p4 <= r_V_7_fu_1184_p2(18 downto 3);
    trunc_ln818_12_fu_1206_p4 <= r_V_8_fu_1200_p2(18 downto 3);
    trunc_ln818_13_fu_1232_p4 <= r_V_9_fu_1226_p2(18 downto 3);
    trunc_ln818_14_fu_1259_p4 <= r_V_10_fu_1253_p2(18 downto 3);
    trunc_ln818_15_fu_1286_p4 <= r_V_11_fu_1280_p2(18 downto 3);
    trunc_ln818_16_fu_1302_p4 <= r_V_12_fu_1296_p2(18 downto 3);
    trunc_ln818_17_fu_1318_p4 <= r_V_13_fu_1312_p2(18 downto 3);
    trunc_ln818_18_fu_687_p4 <= r_V_14_fu_681_p2(18 downto 3);
    trunc_ln818_19_fu_719_p4 <= r_V_15_fu_713_p2(17 downto 3);
    trunc_ln818_1_fu_1084_p4 <= r_V_4_fu_1078_p2(18 downto 3);
    trunc_ln818_20_fu_739_p4 <= r_V_16_fu_733_p2(18 downto 3);
    trunc_ln818_22_fu_779_p4 <= r_V_18_fu_773_p2(18 downto 3);
    trunc_ln818_23_fu_811_p4 <= r_V_19_fu_805_p2(18 downto 3);
    trunc_ln818_24_fu_841_p4 <= r_V_20_fu_835_p2(18 downto 3);
    trunc_ln818_25_fu_851_p1 <= p_read6;
    trunc_ln818_26_fu_861_p1 <= p_read6;
    trunc_ln818_26_fu_861_p4 <= trunc_ln818_26_fu_861_p1(15 downto 1);
    trunc_ln818_2_fu_1111_p4 <= r_V_5_fu_1105_p2(18 downto 3);
    trunc_ln818_3_fu_1121_p4 <= mul_ln1270_1_fu_152_p2(18 downto 3);
    trunc_ln818_4_fu_1147_p4 <= sub_ln1270_fu_1141_p2(18 downto 3);
    trunc_ln818_5_fu_973_p4 <= r_V_1_fu_967_p2(18 downto 3);
    trunc_ln818_6_fu_1000_p4 <= r_V_2_fu_994_p2(18 downto 3);
    trunc_ln818_7_fu_1010_p4 <= mul_ln1270_fu_149_p2(18 downto 3);
    trunc_ln818_8_fu_631_p1 <= p_read1;
    trunc_ln818_8_fu_631_p4 <= trunc_ln818_8_fu_631_p1(15 downto 2);
    trunc_ln818_9_fu_1040_p4 <= r_V_3_fu_1034_p2(18 downto 3);
    trunc_ln818_s_fu_645_p1 <= p_read2;
    trunc_ln818_s_fu_645_p4 <= trunc_ln818_s_fu_645_p1(15 downto 1);
    trunc_ln_fu_944_p4 <= r_V_fu_938_p2(18 downto 3);
end behav;
