// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_linear_ap_fixed_16_6_5_3_0_ap_fixed_8_3_5_3_0_linear_config4_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);


output   ap_ready;
input  [12:0] p_read;
input  [12:0] p_read1;
input  [12:0] p_read2;
input  [12:0] p_read3;
input  [12:0] p_read4;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;

assign ap_ready = 1'b1;

assign ap_return_0 = {{p_read[12:5]}};

assign ap_return_1 = {{p_read1[12:5]}};

assign ap_return_2 = {{p_read2[12:5]}};

assign ap_return_3 = {{p_read3[12:5]}};

assign ap_return_4 = {{p_read4[12:5]}};

endmodule //inference_linear_ap_fixed_16_6_5_3_0_ap_fixed_8_3_5_3_0_linear_config4_s
