// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config11_s (
        ap_ready,
        p_read,
        p_read2,
        p_read3,
        p_read4,
        p_read6,
        p_read9,
        ap_return
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read6;
input  [15:0] p_read9;
output  [15:0] ap_return;

wire   [14:0] trunc_ln_fu_84_p4;
wire   [18:0] shl_ln_fu_98_p3;
wire   [18:0] r_V_fu_106_p2;
wire   [16:0] shl_ln1273_14_fu_130_p3;
wire  signed [18:0] sext_ln1273_fu_138_p1;
wire   [18:0] shl_ln1273_s_fu_122_p3;
wire   [18:0] r_V_21_fu_142_p2;
wire   [18:0] shl_ln1273_15_fu_158_p3;
wire   [18:0] r_V_22_fu_166_p2;
wire   [16:0] shl_ln1273_17_fu_190_p3;
wire  signed [18:0] sext_ln1273_16_fu_198_p1;
wire   [18:0] shl_ln1273_16_fu_182_p3;
wire   [18:0] r_V_23_fu_202_p2;
wire  signed [15:0] sext_ln1270_fu_218_p0;
wire  signed [15:0] p_shl_fu_222_p1;
wire  signed [18:0] sext_ln1270_fu_218_p1;
wire   [18:0] p_shl_fu_222_p3;
wire   [18:0] sub_ln1270_fu_230_p2;
wire   [15:0] trunc_ln818_27_fu_148_p4;
wire   [15:0] trunc_ln818_28_fu_172_p4;
wire   [15:0] add_ln813_fu_246_p2;
wire   [15:0] trunc_ln818_s_fu_112_p4;
wire   [15:0] trunc_ln818_30_fu_236_p4;
wire  signed [15:0] sext_ln818_fu_94_p1;
wire   [15:0] add_ln813_47_fu_258_p2;
wire   [15:0] trunc_ln818_29_fu_208_p4;
wire   [15:0] add_ln813_48_fu_264_p2;
wire   [15:0] add_ln813_46_fu_252_p2;

assign add_ln813_46_fu_252_p2 = (add_ln813_fu_246_p2 + trunc_ln818_s_fu_112_p4);

assign add_ln813_47_fu_258_p2 = ($signed(trunc_ln818_30_fu_236_p4) + $signed(sext_ln818_fu_94_p1));

assign add_ln813_48_fu_264_p2 = (add_ln813_47_fu_258_p2 + trunc_ln818_29_fu_208_p4);

assign add_ln813_fu_246_p2 = (trunc_ln818_27_fu_148_p4 + trunc_ln818_28_fu_172_p4);

assign ap_ready = 1'b1;

assign p_shl_fu_222_p3 = {{p_shl_fu_222_p1}, {3'd0}};

assign r_V_21_fu_142_p2 = ($signed(sext_ln1273_fu_138_p1) - $signed(shl_ln1273_s_fu_122_p3));

assign r_V_22_fu_166_p2 = (19'd0 - shl_ln1273_15_fu_158_p3);

assign r_V_23_fu_202_p2 = ($signed(sext_ln1273_16_fu_198_p1) - $signed(shl_ln1273_16_fu_182_p3));

assign r_V_fu_106_p2 = (19'd0 - shl_ln_fu_98_p3);

assign sext_ln1270_fu_218_p1 = sext_ln1270_fu_218_p0;

assign sext_ln1273_16_fu_198_p1 = $signed(shl_ln1273_17_fu_190_p3);

assign sext_ln1273_fu_138_p1 = $signed(shl_ln1273_14_fu_130_p3);

assign sext_ln818_fu_94_p1 = $signed(trunc_ln_fu_84_p4);

assign shl_ln1273_14_fu_130_p3 = {{p_read3}, {1'd0}};

assign shl_ln1273_15_fu_158_p3 = {{p_read4}, {3'd0}};

assign shl_ln1273_16_fu_182_p3 = {{p_read6}, {3'd0}};

assign shl_ln1273_17_fu_190_p3 = {{p_read6}, {1'd0}};

assign shl_ln1273_s_fu_122_p3 = {{p_read3}, {3'd0}};

assign shl_ln_fu_98_p3 = {{p_read2}, {3'd0}};

assign sub_ln1270_fu_230_p2 = ($signed(sext_ln1270_fu_218_p1) - $signed(p_shl_fu_222_p3));

assign trunc_ln818_27_fu_148_p4 = {{r_V_21_fu_142_p2[18:3]}};

assign trunc_ln818_28_fu_172_p4 = {{r_V_22_fu_166_p2[18:3]}};

assign trunc_ln818_29_fu_208_p4 = {{r_V_23_fu_202_p2[18:3]}};

assign trunc_ln818_30_fu_236_p4 = {{sub_ln1270_fu_230_p2[18:3]}};

assign trunc_ln818_s_fu_112_p4 = {{r_V_fu_106_p2[18:3]}};

assign trunc_ln_fu_84_p4 = {{p_read[15:1]}};

assign ap_return = (add_ln813_48_fu_264_p2 + add_ln813_46_fu_252_p2);

assign p_shl_fu_222_p1 = p_read9;

assign sext_ln1270_fu_218_p0 = p_read9;

endmodule //inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config11_s
