// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_linear_ap_fixed_8_2_5_3_0_ap_fixed_16_6_5_3_0_linear_config3_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);


output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;

wire   [11:0] shl_ln_fu_56_p3;
wire   [11:0] shl_ln838_1_fu_68_p3;
wire   [11:0] shl_ln838_2_fu_80_p3;
wire   [11:0] shl_ln838_3_fu_92_p3;
wire   [11:0] shl_ln838_4_fu_104_p3;
wire  signed [15:0] sext_ln837_fu_64_p1;
wire  signed [15:0] sext_ln837_1_fu_76_p1;
wire  signed [15:0] sext_ln837_2_fu_88_p1;
wire  signed [15:0] sext_ln837_3_fu_100_p1;
wire  signed [15:0] sext_ln34_fu_112_p1;

assign ap_ready = 1'b1;

assign sext_ln34_fu_112_p1 = $signed(shl_ln838_4_fu_104_p3);

assign sext_ln837_1_fu_76_p1 = $signed(shl_ln838_1_fu_68_p3);

assign sext_ln837_2_fu_88_p1 = $signed(shl_ln838_2_fu_80_p3);

assign sext_ln837_3_fu_100_p1 = $signed(shl_ln838_3_fu_92_p3);

assign sext_ln837_fu_64_p1 = $signed(shl_ln_fu_56_p3);

assign shl_ln838_1_fu_68_p3 = {{p_read1}, {4'd0}};

assign shl_ln838_2_fu_80_p3 = {{p_read2}, {4'd0}};

assign shl_ln838_3_fu_92_p3 = {{p_read3}, {4'd0}};

assign shl_ln838_4_fu_104_p3 = {{p_read4}, {4'd0}};

assign shl_ln_fu_56_p3 = {{p_read}, {4'd0}};

assign ap_return_0 = sext_ln837_fu_64_p1;

assign ap_return_1 = sext_ln837_1_fu_76_p1;

assign ap_return_2 = sext_ln837_2_fu_88_p1;

assign ap_return_3 = sext_ln837_3_fu_100_p1;

assign ap_return_4 = sext_ln34_fu_112_p1;

endmodule //inference_linear_ap_fixed_8_2_5_3_0_ap_fixed_16_6_5_3_0_linear_config3_s
