# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MLZedboard/MLZedboard.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLZedboard || ORIG_REF_NAME==MLZedboard} -quiet] -quiet

# IP: bd/MLZedboard/ip/MLZedboard_comblock_0_0/MLZedboard_comblock_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLZedboard_comblock_0_0 || ORIG_REF_NAME==MLZedboard_comblock_0_0} -quiet] -quiet

# IP: bd/MLZedboard/ip/MLZedboard_inference_0_0/MLZedboard_inference_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLZedboard_inference_0_0 || ORIG_REF_NAME==MLZedboard_inference_0_0} -quiet] -quiet

# IP: bd/MLZedboard/ip/MLZedboard_processing_system7_0_0/MLZedboard_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLZedboard_processing_system7_0_0 || ORIG_REF_NAME==MLZedboard_processing_system7_0_0} -quiet] -quiet

# IP: bd/MLZedboard/ip/MLZedboard_auto_pc_0/MLZedboard_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLZedboard_auto_pc_0 || ORIG_REF_NAME==MLZedboard_auto_pc_0} -quiet] -quiet

# IP: bd/MLZedboard/ip/MLZedboard_ps7_0_axi_periph_0/MLZedboard_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLZedboard_ps7_0_axi_periph_0 || ORIG_REF_NAME==MLZedboard_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/MLZedboard/ip/MLZedboard_rst_ps7_0_100M_0/MLZedboard_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLZedboard_rst_ps7_0_100M_0 || ORIG_REF_NAME==MLZedboard_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/MLZedboard/ip/MLZedboard_xlconstant_0_0/MLZedboard_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLZedboard_xlconstant_0_0 || ORIG_REF_NAME==MLZedboard_xlconstant_0_0} -quiet] -quiet

# IP: bd/MLZedboard/ip/MLZedboard_xlconstant_1_0/MLZedboard_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLZedboard_xlconstant_1_0 || ORIG_REF_NAME==MLZedboard_xlconstant_1_0} -quiet] -quiet

# XDC: /home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.gen/sources_1/bd/MLZedboard/MLZedboard_ooc.xdc
