// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_16_6_5_3_0_config5_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);


input   ap_clk;
input   ap_rst;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;

wire   [13:0] mul_ln841_1_fu_116_p2;
reg   [13:0] mul_ln841_1_reg_236;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] p_read_14_reg_1095;
reg  signed [7:0] p_read_15_reg_1102;
reg  signed [7:0] p_read215_reg_1112;
reg  signed [7:0] p_read114_reg_1121;
reg  signed [7:0] p_read13_reg_1129;
wire  signed [13:0] sext_ln841_12_fu_471_p1;
reg  signed [13:0] sext_ln841_12_reg_1137;
wire   [5:0] mul_ln841_fu_95_p1;
wire    ap_block_pp0_stage0;
wire  signed [7:0] mul_ln841_2_fu_97_p0;
wire  signed [5:0] mul_ln841_2_fu_97_p1;
wire  signed [5:0] mul_ln841_1_fu_116_p1;
wire  signed [7:0] sext_ln841_12_fu_471_p0;
wire   [10:0] shl_ln_fu_476_p3;
wire  signed [8:0] shl_ln841_1_fu_487_p3;
wire  signed [11:0] sext_ln841_2_fu_498_p1;
wire  signed [11:0] sext_ln841_fu_483_p1;
wire   [11:0] sub_ln841_fu_502_p2;
wire   [11:0] shl_ln841_2_fu_512_p3;
wire  signed [12:0] sext_ln841_4_fu_519_p1;
wire  signed [12:0] sext_ln841_1_fu_494_p1;
wire  signed [12:0] add_ln841_fu_523_p2;
wire   [12:0] sub_ln841_1_fu_533_p2;
wire  signed [12:0] sub_ln841_2_fu_539_p2;
wire   [12:0] sub_ln841_3_fu_549_p2;
wire   [9:0] shl_ln841_3_fu_563_p3;
wire  signed [10:0] r_V_fu_574_p3;
wire  signed [11:0] sext_ln841_10_fu_585_p1;
wire   [8:0] shl_ln841_5_fu_595_p3;
wire   [11:0] sub_ln841_4_fu_589_p2;
wire  signed [11:0] sext_ln841_11_fu_602_p1;
wire   [11:0] sub_ln841_5_fu_606_p2;
wire   [12:0] shl_ln841_6_fu_616_p3;
wire   [10:0] shl_ln841_7_fu_627_p3;
wire  signed [13:0] sext_ln841_13_fu_623_p1;
wire  signed [13:0] sext_ln841_14_fu_634_p1;
wire   [11:0] shl_ln841_8_fu_644_p3;
wire   [9:0] shl_ln841_9_fu_655_p3;
wire  signed [12:0] sext_ln841_15_fu_651_p1;
wire  signed [12:0] sext_ln841_16_fu_662_p1;
wire   [12:0] sub_ln841_7_fu_666_p2;
wire   [11:0] shl_ln841_s_fu_676_p3;
wire  signed [8:0] shl_ln841_4_fu_687_p3;
wire  signed [12:0] sext_ln841_18_fu_683_p1;
wire  signed [12:0] sext_ln841_20_fu_698_p1;
wire   [12:0] sub_ln841_8_fu_702_p2;
wire   [9:0] shl_ln841_10_fu_718_p3;
wire   [12:0] sub_ln841_9_fu_712_p2;
wire  signed [12:0] sext_ln841_22_fu_725_p1;
wire  signed [12:0] sub_ln841_10_fu_729_p2;
wire   [12:0] shl_ln841_11_fu_739_p3;
wire   [10:0] shl_ln841_12_fu_750_p3;
wire  signed [13:0] sext_ln841_24_fu_746_p1;
wire  signed [13:0] sext_ln841_25_fu_757_p1;
wire   [11:0] shl_ln841_13_fu_767_p3;
wire   [9:0] shl_ln841_14_fu_778_p3;
wire  signed [12:0] sext_ln841_27_fu_785_p1;
wire  signed [12:0] sext_ln841_26_fu_774_p1;
wire  signed [12:0] sub_ln841_12_fu_789_p2;
wire   [8:0] shl_ln841_15_fu_799_p3;
wire   [12:0] sub_ln841_13_fu_810_p2;
wire   [13:0] mul_ln841_2_fu_97_p2;
wire  signed [13:0] sext_ln841_5_fu_529_p1;
wire   [13:0] add_ln813_fu_820_p2;
wire  signed [8:0] p_read3_cast26_fu_833_p1;
wire  signed [8:0] p_read2_cast27_fu_830_p1;
wire   [8:0] tmp14_fu_836_p2;
wire   [9:0] tmp_fu_842_p3;
wire  signed [12:0] sext_ln813_7_fu_850_p1;
wire   [12:0] add_ln813_1_fu_854_p2;
wire  signed [13:0] sext_ln813_11_fu_860_p1;
wire   [13:0] mul_ln841_fu_95_p2;
wire   [13:0] add_ln813_2_fu_864_p2;
wire  signed [12:0] sext_ln841_3_fu_508_p1;
wire   [12:0] add_ln813_3_fu_874_p2;
wire  signed [13:0] sext_ln813_1_fu_880_p1;
wire  signed [13:0] sext_ln841_21_fu_708_p1;
wire   [13:0] add_ln813_4_fu_884_p2;
wire  signed [12:0] sext_ln841_8_fu_570_p1;
wire   [12:0] sub_ln813_fu_894_p2;
wire  signed [13:0] sext_ln813_3_fu_900_p1;
wire   [13:0] sub_ln841_6_fu_638_p2;
wire   [13:0] add_ln813_5_fu_904_p2;
wire  signed [12:0] sext_ln841_29_fu_806_p1;
wire   [12:0] add_ln813_6_fu_914_p2;
wire  signed [13:0] sext_ln813_5_fu_920_p1;
wire  signed [13:0] sext_ln841_23_fu_735_p1;
wire   [13:0] add_ln813_8_fu_924_p2;
wire  signed [14:0] sext_ln813_6_fu_930_p1;
wire  signed [14:0] sext_ln813_4_fu_910_p1;
wire   [14:0] add_ln813_7_fu_934_p2;
wire  signed [8:0] p_read_cast29_fu_944_p1;
wire   [8:0] tmp5212_fu_947_p2;
wire   [10:0] tmp_4_fu_953_p3;
wire  signed [12:0] sext_ln813_13_fu_961_p1;
wire  signed [12:0] sext_ln1270_fu_612_p1;
wire   [12:0] add_ln813_9_fu_965_p2;
wire   [13:0] sub_ln841_11_fu_761_p2;
wire  signed [13:0] sext_ln841_28_fu_795_p1;
wire   [13:0] add_ln813_11_fu_975_p2;
wire  signed [14:0] sext_ln813_15_fu_981_p1;
wire  signed [14:0] sext_ln813_14_fu_971_p1;
wire   [14:0] add_ln813_10_fu_985_p2;
wire  signed [13:0] sext_ln841_17_fu_672_p1;
wire  signed [13:0] sext_ln841_6_fu_545_p1;
wire   [12:0] add_ln813_14_fu_1001_p2;
wire  signed [13:0] sext_ln813_8_fu_1007_p1;
wire   [13:0] add_ln813_12_fu_995_p2;
wire   [13:0] add_ln813_13_fu_1011_p2;
wire  signed [13:0] sext_ln70_fu_555_p1;
wire   [13:0] add_ln813_17_fu_1021_p2;
wire  signed [13:0] sext_ln841_9_fu_581_p1;
wire   [13:0] add_ln813_15_fu_1027_p2;
wire  signed [13:0] sext_ln841_19_fu_694_p1;
wire   [13:0] sub_ln813_1_fu_1033_p2;
wire  signed [14:0] sext_ln813_10_fu_1039_p1;
wire  signed [14:0] sext_ln813_fu_816_p1;
wire   [14:0] add_ln813_16_fu_1043_p2;
wire  signed [15:0] sext_ln813_2_fu_890_p1;
wire  signed [15:0] add_ln813_7_cast_fu_940_p1;
wire  signed [15:0] sext_ln813_12_fu_870_p1;
wire  signed [15:0] sext_ln813_16_fu_991_p1;
wire  signed [15:0] sext_ln813_9_fu_1017_p1;
wire  signed [15:0] sext_ln68_fu_1049_p1;
wire  signed [15:0] add_ln813_cast_fu_826_p1;
wire    ap_ce_reg;

inference_mul_8s_6ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6ns_14_1_1_U767(
    .din0(p_read114_reg_1121),
    .din1(mul_ln841_fu_95_p1),
    .dout(mul_ln841_fu_95_p2)
);

inference_mul_8s_6s_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6s_14_1_1_U768(
    .din0(mul_ln841_2_fu_97_p0),
    .din1(mul_ln841_2_fu_97_p1),
    .dout(mul_ln841_2_fu_97_p2)
);

inference_mul_8s_6s_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 14 ))
mul_8s_6s_14_1_1_U769(
    .din0(p_read2),
    .din1(mul_ln841_1_fu_116_p1),
    .dout(mul_ln841_1_fu_116_p2)
);

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        mul_ln841_1_reg_236 <= mul_ln841_1_fu_116_p2;
        p_read114_reg_1121 <= p_read1;
        p_read13_reg_1129 <= p_read;
        p_read215_reg_1112 <= p_read2;
        p_read_14_reg_1095 <= p_read4;
        p_read_15_reg_1102 <= p_read3;
        sext_ln841_12_reg_1137 <= sext_ln841_12_fu_471_p1;
    end
end

assign add_ln813_10_fu_985_p2 = ($signed(sext_ln813_15_fu_981_p1) + $signed(sext_ln813_14_fu_971_p1));

assign add_ln813_11_fu_975_p2 = ($signed(sub_ln841_11_fu_761_p2) + $signed(sext_ln841_28_fu_795_p1));

assign add_ln813_12_fu_995_p2 = ($signed(sext_ln841_17_fu_672_p1) + $signed(sext_ln841_6_fu_545_p1));

assign add_ln813_13_fu_1011_p2 = ($signed(sext_ln813_8_fu_1007_p1) + $signed(add_ln813_12_fu_995_p2));

assign add_ln813_14_fu_1001_p2 = ($signed(sub_ln841_10_fu_729_p2) + $signed(sext_ln841_29_fu_806_p1));

assign add_ln813_15_fu_1027_p2 = ($signed(add_ln813_17_fu_1021_p2) + $signed(sext_ln841_9_fu_581_p1));

assign add_ln813_16_fu_1043_p2 = ($signed(sext_ln813_10_fu_1039_p1) + $signed(sext_ln813_fu_816_p1));

assign add_ln813_17_fu_1021_p2 = ($signed(sext_ln70_fu_555_p1) + $signed(mul_ln841_1_reg_236));

assign add_ln813_1_fu_854_p2 = ($signed(sub_ln841_2_fu_539_p2) + $signed(sext_ln813_7_fu_850_p1));

assign add_ln813_2_fu_864_p2 = ($signed(sext_ln813_11_fu_860_p1) + $signed(mul_ln841_fu_95_p2));

assign add_ln813_3_fu_874_p2 = ($signed(sext_ln841_3_fu_508_p1) + $signed(sub_ln841_12_fu_789_p2));

assign add_ln813_4_fu_884_p2 = ($signed(sext_ln813_1_fu_880_p1) + $signed(sext_ln841_21_fu_708_p1));

assign add_ln813_5_fu_904_p2 = ($signed(sext_ln813_3_fu_900_p1) + $signed(sub_ln841_6_fu_638_p2));

assign add_ln813_6_fu_914_p2 = ($signed(sext_ln841_29_fu_806_p1) + $signed(sext_ln841_26_fu_774_p1));

assign add_ln813_7_cast_fu_940_p1 = $signed(add_ln813_7_fu_934_p2);

assign add_ln813_7_fu_934_p2 = ($signed(sext_ln813_6_fu_930_p1) + $signed(sext_ln813_4_fu_910_p1));

assign add_ln813_8_fu_924_p2 = ($signed(sext_ln813_5_fu_920_p1) + $signed(sext_ln841_23_fu_735_p1));

assign add_ln813_9_fu_965_p2 = ($signed(sext_ln813_13_fu_961_p1) + $signed(sext_ln1270_fu_612_p1));

assign add_ln813_cast_fu_826_p1 = $signed(add_ln813_fu_820_p2);

assign add_ln813_fu_820_p2 = ($signed(mul_ln841_2_fu_97_p2) + $signed(sext_ln841_5_fu_529_p1));

assign add_ln841_fu_523_p2 = ($signed(sext_ln841_4_fu_519_p1) + $signed(sext_ln841_1_fu_494_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_return_0 = sext_ln813_2_fu_890_p1;

assign ap_return_1 = add_ln813_7_cast_fu_940_p1;

assign ap_return_2 = sext_ln813_12_fu_870_p1;

assign ap_return_3 = sext_ln813_16_fu_991_p1;

assign ap_return_4 = sext_ln813_9_fu_1017_p1;

assign ap_return_5 = sext_ln68_fu_1049_p1;

assign ap_return_6 = add_ln813_cast_fu_826_p1;

assign mul_ln841_1_fu_116_p1 = 14'd16358;

assign mul_ln841_2_fu_97_p0 = sext_ln841_12_reg_1137;

assign mul_ln841_2_fu_97_p1 = 14'd16362;

assign mul_ln841_fu_95_p1 = 14'd22;

assign p_read2_cast27_fu_830_p1 = p_read215_reg_1112;

assign p_read3_cast26_fu_833_p1 = p_read_15_reg_1102;

assign p_read_cast29_fu_944_p1 = p_read13_reg_1129;

assign r_V_fu_574_p3 = {{p_read114_reg_1121}, {3'd0}};

assign sext_ln1270_fu_612_p1 = $signed(sub_ln841_5_fu_606_p2);

assign sext_ln68_fu_1049_p1 = $signed(add_ln813_16_fu_1043_p2);

assign sext_ln70_fu_555_p1 = $signed(sub_ln841_3_fu_549_p2);

assign sext_ln813_10_fu_1039_p1 = $signed(sub_ln813_1_fu_1033_p2);

assign sext_ln813_11_fu_860_p1 = $signed(add_ln813_1_fu_854_p2);

assign sext_ln813_12_fu_870_p1 = $signed(add_ln813_2_fu_864_p2);

assign sext_ln813_13_fu_961_p1 = $signed(tmp_4_fu_953_p3);

assign sext_ln813_14_fu_971_p1 = $signed(add_ln813_9_fu_965_p2);

assign sext_ln813_15_fu_981_p1 = $signed(add_ln813_11_fu_975_p2);

assign sext_ln813_16_fu_991_p1 = $signed(add_ln813_10_fu_985_p2);

assign sext_ln813_1_fu_880_p1 = $signed(add_ln813_3_fu_874_p2);

assign sext_ln813_2_fu_890_p1 = $signed(add_ln813_4_fu_884_p2);

assign sext_ln813_3_fu_900_p1 = $signed(sub_ln813_fu_894_p2);

assign sext_ln813_4_fu_910_p1 = $signed(add_ln813_5_fu_904_p2);

assign sext_ln813_5_fu_920_p1 = $signed(add_ln813_6_fu_914_p2);

assign sext_ln813_6_fu_930_p1 = $signed(add_ln813_8_fu_924_p2);

assign sext_ln813_7_fu_850_p1 = $signed(tmp_fu_842_p3);

assign sext_ln813_8_fu_1007_p1 = $signed(add_ln813_14_fu_1001_p2);

assign sext_ln813_9_fu_1017_p1 = $signed(add_ln813_13_fu_1011_p2);

assign sext_ln813_fu_816_p1 = $signed(sub_ln841_13_fu_810_p2);

assign sext_ln841_10_fu_585_p1 = r_V_fu_574_p3;

assign sext_ln841_11_fu_602_p1 = $signed(shl_ln841_5_fu_595_p3);

assign sext_ln841_12_fu_471_p0 = p_read2;

assign sext_ln841_12_fu_471_p1 = sext_ln841_12_fu_471_p0;

assign sext_ln841_13_fu_623_p1 = $signed(shl_ln841_6_fu_616_p3);

assign sext_ln841_14_fu_634_p1 = $signed(shl_ln841_7_fu_627_p3);

assign sext_ln841_15_fu_651_p1 = $signed(shl_ln841_8_fu_644_p3);

assign sext_ln841_16_fu_662_p1 = $signed(shl_ln841_9_fu_655_p3);

assign sext_ln841_17_fu_672_p1 = $signed(sub_ln841_7_fu_666_p2);

assign sext_ln841_18_fu_683_p1 = $signed(shl_ln841_s_fu_676_p3);

assign sext_ln841_19_fu_694_p1 = shl_ln841_4_fu_687_p3;

assign sext_ln841_1_fu_494_p1 = shl_ln841_1_fu_487_p3;

assign sext_ln841_20_fu_698_p1 = shl_ln841_4_fu_687_p3;

assign sext_ln841_21_fu_708_p1 = $signed(sub_ln841_8_fu_702_p2);

assign sext_ln841_22_fu_725_p1 = $signed(shl_ln841_10_fu_718_p3);

assign sext_ln841_23_fu_735_p1 = sub_ln841_10_fu_729_p2;

assign sext_ln841_24_fu_746_p1 = $signed(shl_ln841_11_fu_739_p3);

assign sext_ln841_25_fu_757_p1 = $signed(shl_ln841_12_fu_750_p3);

assign sext_ln841_26_fu_774_p1 = $signed(shl_ln841_13_fu_767_p3);

assign sext_ln841_27_fu_785_p1 = $signed(shl_ln841_14_fu_778_p3);

assign sext_ln841_28_fu_795_p1 = sub_ln841_12_fu_789_p2;

assign sext_ln841_29_fu_806_p1 = $signed(shl_ln841_15_fu_799_p3);

assign sext_ln841_2_fu_498_p1 = shl_ln841_1_fu_487_p3;

assign sext_ln841_3_fu_508_p1 = $signed(sub_ln841_fu_502_p2);

assign sext_ln841_4_fu_519_p1 = $signed(shl_ln841_2_fu_512_p3);

assign sext_ln841_5_fu_529_p1 = add_ln841_fu_523_p2;

assign sext_ln841_6_fu_545_p1 = sub_ln841_2_fu_539_p2;

assign sext_ln841_8_fu_570_p1 = $signed(shl_ln841_3_fu_563_p3);

assign sext_ln841_9_fu_581_p1 = r_V_fu_574_p3;

assign sext_ln841_fu_483_p1 = $signed(shl_ln_fu_476_p3);

assign shl_ln841_10_fu_718_p3 = {{p_read_15_reg_1102}, {2'd0}};

assign shl_ln841_11_fu_739_p3 = {{p_read_15_reg_1102}, {5'd0}};

assign shl_ln841_12_fu_750_p3 = {{p_read_15_reg_1102}, {3'd0}};

assign shl_ln841_13_fu_767_p3 = {{p_read_14_reg_1095}, {4'd0}};

assign shl_ln841_14_fu_778_p3 = {{p_read_14_reg_1095}, {2'd0}};

assign shl_ln841_15_fu_799_p3 = {{p_read_14_reg_1095}, {1'd0}};

assign shl_ln841_1_fu_487_p3 = {{p_read13_reg_1129}, {1'd0}};

assign shl_ln841_2_fu_512_p3 = {{p_read13_reg_1129}, {4'd0}};

assign shl_ln841_3_fu_563_p3 = {{p_read114_reg_1121}, {2'd0}};

assign shl_ln841_4_fu_687_p3 = {{p_read_15_reg_1102}, {1'd0}};

assign shl_ln841_5_fu_595_p3 = {{p_read114_reg_1121}, {1'd0}};

assign shl_ln841_6_fu_616_p3 = {{p_read215_reg_1112}, {5'd0}};

assign shl_ln841_7_fu_627_p3 = {{p_read215_reg_1112}, {3'd0}};

assign shl_ln841_8_fu_644_p3 = {{p_read215_reg_1112}, {4'd0}};

assign shl_ln841_9_fu_655_p3 = {{p_read215_reg_1112}, {2'd0}};

assign shl_ln841_s_fu_676_p3 = {{p_read_15_reg_1102}, {4'd0}};

assign shl_ln_fu_476_p3 = {{p_read13_reg_1129}, {3'd0}};

assign sub_ln813_1_fu_1033_p2 = ($signed(add_ln813_15_fu_1027_p2) - $signed(sext_ln841_19_fu_694_p1));

assign sub_ln813_fu_894_p2 = ($signed(add_ln841_fu_523_p2) - $signed(sext_ln841_8_fu_570_p1));

assign sub_ln841_10_fu_729_p2 = ($signed(sub_ln841_9_fu_712_p2) - $signed(sext_ln841_22_fu_725_p1));

assign sub_ln841_11_fu_761_p2 = ($signed(sext_ln841_24_fu_746_p1) - $signed(sext_ln841_25_fu_757_p1));

assign sub_ln841_12_fu_789_p2 = ($signed(sext_ln841_27_fu_785_p1) - $signed(sext_ln841_26_fu_774_p1));

assign sub_ln841_13_fu_810_p2 = ($signed(sext_ln841_26_fu_774_p1) - $signed(sext_ln841_27_fu_785_p1));

assign sub_ln841_1_fu_533_p2 = ($signed(13'd0) - $signed(sext_ln841_4_fu_519_p1));

assign sub_ln841_2_fu_539_p2 = ($signed(sub_ln841_1_fu_533_p2) - $signed(sext_ln841_1_fu_494_p1));

assign sub_ln841_3_fu_549_p2 = ($signed(sext_ln841_1_fu_494_p1) - $signed(sext_ln841_4_fu_519_p1));

assign sub_ln841_4_fu_589_p2 = ($signed(12'd0) - $signed(sext_ln841_10_fu_585_p1));

assign sub_ln841_5_fu_606_p2 = ($signed(sub_ln841_4_fu_589_p2) - $signed(sext_ln841_11_fu_602_p1));

assign sub_ln841_6_fu_638_p2 = ($signed(sext_ln841_13_fu_623_p1) - $signed(sext_ln841_14_fu_634_p1));

assign sub_ln841_7_fu_666_p2 = ($signed(sext_ln841_15_fu_651_p1) - $signed(sext_ln841_16_fu_662_p1));

assign sub_ln841_8_fu_702_p2 = ($signed(sext_ln841_18_fu_683_p1) - $signed(sext_ln841_20_fu_698_p1));

assign sub_ln841_9_fu_712_p2 = ($signed(13'd0) - $signed(sext_ln841_18_fu_683_p1));

assign sub_ln841_fu_502_p2 = ($signed(sext_ln841_2_fu_498_p1) - $signed(sext_ln841_fu_483_p1));

assign tmp14_fu_836_p2 = ($signed(p_read3_cast26_fu_833_p1) + $signed(p_read2_cast27_fu_830_p1));

assign tmp5212_fu_947_p2 = ($signed(p_read2_cast27_fu_830_p1) - $signed(p_read_cast29_fu_944_p1));

assign tmp_4_fu_953_p3 = {{tmp5212_fu_947_p2}, {2'd0}};

assign tmp_fu_842_p3 = {{tmp14_fu_836_p2}, {1'd0}};

endmodule //inference_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_16_6_5_3_0_config5_s
