set_property SRC_FILE_INFO {cfile:/home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.gen/sources_1/bd/MLZedboard/ip/MLZedboard_inference_0_0/constraints/inference_ooc.xdc rfile:../../../../../Lab08-01.gen/sources_1/bd/MLZedboard/ip/MLZedboard_inference_0_0/constraints/inference_ooc.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.runs/MLZedboard_inference_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 12.000 -name ap_clk [get_ports ap_clk]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
