-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_16_6_5_3_0_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of inference_dense_latency_ap_fixed_8_3_5_3_0_ap_fixed_16_6_5_3_0_config5_s is 
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv14_16 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010110";
    constant ap_const_lv14_3FEA : STD_LOGIC_VECTOR (13 downto 0) := "11111111101010";
    constant ap_const_lv14_3FE6 : STD_LOGIC_VECTOR (13 downto 0) := "11111111100110";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal mul_ln841_1_fu_116_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln841_1_reg_236 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_read_14_reg_1095 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read_15_reg_1102 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read215_reg_1112 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read114_reg_1121 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_read13_reg_1129 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln841_12_fu_471_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_12_reg_1137 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln841_fu_95_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln841_2_fu_97_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln841_2_fu_97_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln841_1_fu_116_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln841_12_fu_471_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_fu_476_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln841_1_fu_487_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln841_2_fu_498_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln841_fu_483_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln841_fu_502_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln841_2_fu_512_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln841_4_fu_519_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln841_1_fu_494_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln841_fu_523_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln841_1_fu_533_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln841_2_fu_539_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln841_3_fu_549_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln841_3_fu_563_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_fu_574_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln841_10_fu_585_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln841_5_fu_595_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln841_4_fu_589_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln841_11_fu_602_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln841_5_fu_606_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln841_6_fu_616_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln841_7_fu_627_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln841_13_fu_623_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_14_fu_634_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln841_8_fu_644_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln841_9_fu_655_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln841_15_fu_651_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln841_16_fu_662_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln841_7_fu_666_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln841_s_fu_676_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln841_4_fu_687_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln841_18_fu_683_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln841_20_fu_698_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln841_8_fu_702_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln841_10_fu_718_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln841_9_fu_712_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln841_22_fu_725_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln841_10_fu_729_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln841_11_fu_739_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln841_12_fu_750_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln841_24_fu_746_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_25_fu_757_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln841_13_fu_767_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln841_14_fu_778_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln841_27_fu_785_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln841_26_fu_774_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln841_12_fu_789_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln841_15_fu_799_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln841_13_fu_810_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln841_2_fu_97_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_5_fu_529_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_fu_820_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_read3_cast26_fu_833_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read2_cast27_fu_830_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp14_fu_836_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_842_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln813_7_fu_850_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln813_1_fu_854_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln813_11_fu_860_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln841_fu_95_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_2_fu_864_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_3_fu_508_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln813_3_fu_874_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln813_1_fu_880_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_21_fu_708_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_4_fu_884_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_8_fu_570_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln813_fu_894_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln813_3_fu_900_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln841_6_fu_638_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_5_fu_904_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_29_fu_806_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln813_6_fu_914_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln813_5_fu_920_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_23_fu_735_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_8_fu_924_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln813_6_fu_930_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln813_4_fu_910_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln813_7_fu_934_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_read_cast29_fu_944_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp5212_fu_947_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_4_fu_953_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln813_13_fu_961_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln1270_fu_612_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln813_9_fu_965_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln841_11_fu_761_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_28_fu_795_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_11_fu_975_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln813_15_fu_981_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln813_14_fu_971_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln813_10_fu_985_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln841_17_fu_672_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_6_fu_545_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_14_fu_1001_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln813_8_fu_1007_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_12_fu_995_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_13_fu_1011_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln70_fu_555_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_17_fu_1021_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_9_fu_581_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_15_fu_1027_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln841_19_fu_694_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln813_1_fu_1033_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln813_10_fu_1039_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln813_fu_816_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln813_16_fu_1043_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln813_2_fu_890_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_7_cast_fu_940_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln813_12_fu_870_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln813_16_fu_991_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln813_9_fu_1017_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln68_fu_1049_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_cast_fu_826_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component inference_mul_8s_6ns_14_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;


    component inference_mul_8s_6s_14_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;



begin
    mul_8s_6ns_14_1_1_U767 : component inference_mul_8s_6ns_14_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 6,
        dout_WIDTH => 14)
    port map (
        din0 => p_read114_reg_1121,
        din1 => mul_ln841_fu_95_p1,
        dout => mul_ln841_fu_95_p2);

    mul_8s_6s_14_1_1_U768 : component inference_mul_8s_6s_14_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 6,
        dout_WIDTH => 14)
    port map (
        din0 => mul_ln841_2_fu_97_p0,
        din1 => mul_ln841_2_fu_97_p1,
        dout => mul_ln841_2_fu_97_p2);

    mul_8s_6s_14_1_1_U769 : component inference_mul_8s_6s_14_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 6,
        dout_WIDTH => 14)
    port map (
        din0 => p_read2,
        din1 => mul_ln841_1_fu_116_p1,
        dout => mul_ln841_1_fu_116_p2);




    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                mul_ln841_1_reg_236 <= mul_ln841_1_fu_116_p2;
                p_read114_reg_1121 <= p_read1;
                p_read13_reg_1129 <= p_read;
                p_read215_reg_1112 <= p_read2;
                p_read_14_reg_1095 <= p_read4;
                p_read_15_reg_1102 <= p_read3;
                sext_ln841_12_reg_1137 <= sext_ln841_12_fu_471_p1;
            end if;
        end if;
    end process;
    add_ln813_10_fu_985_p2 <= std_logic_vector(signed(sext_ln813_15_fu_981_p1) + signed(sext_ln813_14_fu_971_p1));
    add_ln813_11_fu_975_p2 <= std_logic_vector(unsigned(sub_ln841_11_fu_761_p2) + unsigned(sext_ln841_28_fu_795_p1));
    add_ln813_12_fu_995_p2 <= std_logic_vector(signed(sext_ln841_17_fu_672_p1) + signed(sext_ln841_6_fu_545_p1));
    add_ln813_13_fu_1011_p2 <= std_logic_vector(signed(sext_ln813_8_fu_1007_p1) + signed(add_ln813_12_fu_995_p2));
    add_ln813_14_fu_1001_p2 <= std_logic_vector(signed(sub_ln841_10_fu_729_p2) + signed(sext_ln841_29_fu_806_p1));
    add_ln813_15_fu_1027_p2 <= std_logic_vector(unsigned(add_ln813_17_fu_1021_p2) + unsigned(sext_ln841_9_fu_581_p1));
    add_ln813_16_fu_1043_p2 <= std_logic_vector(signed(sext_ln813_10_fu_1039_p1) + signed(sext_ln813_fu_816_p1));
    add_ln813_17_fu_1021_p2 <= std_logic_vector(signed(sext_ln70_fu_555_p1) + signed(mul_ln841_1_reg_236));
    add_ln813_1_fu_854_p2 <= std_logic_vector(signed(sub_ln841_2_fu_539_p2) + signed(sext_ln813_7_fu_850_p1));
    add_ln813_2_fu_864_p2 <= std_logic_vector(signed(sext_ln813_11_fu_860_p1) + signed(mul_ln841_fu_95_p2));
    add_ln813_3_fu_874_p2 <= std_logic_vector(signed(sext_ln841_3_fu_508_p1) + signed(sub_ln841_12_fu_789_p2));
    add_ln813_4_fu_884_p2 <= std_logic_vector(signed(sext_ln813_1_fu_880_p1) + signed(sext_ln841_21_fu_708_p1));
    add_ln813_5_fu_904_p2 <= std_logic_vector(signed(sext_ln813_3_fu_900_p1) + signed(sub_ln841_6_fu_638_p2));
    add_ln813_6_fu_914_p2 <= std_logic_vector(signed(sext_ln841_29_fu_806_p1) + signed(sext_ln841_26_fu_774_p1));
        add_ln813_7_cast_fu_940_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_7_fu_934_p2),16));

    add_ln813_7_fu_934_p2 <= std_logic_vector(signed(sext_ln813_6_fu_930_p1) + signed(sext_ln813_4_fu_910_p1));
    add_ln813_8_fu_924_p2 <= std_logic_vector(signed(sext_ln813_5_fu_920_p1) + signed(sext_ln841_23_fu_735_p1));
    add_ln813_9_fu_965_p2 <= std_logic_vector(signed(sext_ln813_13_fu_961_p1) + signed(sext_ln1270_fu_612_p1));
        add_ln813_cast_fu_826_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_fu_820_p2),16));

    add_ln813_fu_820_p2 <= std_logic_vector(unsigned(mul_ln841_2_fu_97_p2) + unsigned(sext_ln841_5_fu_529_p1));
    add_ln841_fu_523_p2 <= std_logic_vector(signed(sext_ln841_4_fu_519_p1) + signed(sext_ln841_1_fu_494_p1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return_0 <= sext_ln813_2_fu_890_p1;
    ap_return_1 <= add_ln813_7_cast_fu_940_p1;
    ap_return_2 <= sext_ln813_12_fu_870_p1;
    ap_return_3 <= sext_ln813_16_fu_991_p1;
    ap_return_4 <= sext_ln813_9_fu_1017_p1;
    ap_return_5 <= sext_ln68_fu_1049_p1;
    ap_return_6 <= add_ln813_cast_fu_826_p1;
    mul_ln841_1_fu_116_p1 <= ap_const_lv14_3FE6(6 - 1 downto 0);
    mul_ln841_2_fu_97_p0 <= sext_ln841_12_reg_1137(8 - 1 downto 0);
    mul_ln841_2_fu_97_p1 <= ap_const_lv14_3FEA(6 - 1 downto 0);
    mul_ln841_fu_95_p1 <= ap_const_lv14_16(6 - 1 downto 0);
        p_read2_cast27_fu_830_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read215_reg_1112),9));

        p_read3_cast26_fu_833_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read_15_reg_1102),9));

        p_read_cast29_fu_944_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read13_reg_1129),9));

    r_V_fu_574_p3 <= (p_read114_reg_1121 & ap_const_lv3_0);
        sext_ln1270_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln841_5_fu_606_p2),13));

        sext_ln68_fu_1049_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_16_fu_1043_p2),16));

        sext_ln70_fu_555_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln841_3_fu_549_p2),14));

        sext_ln813_10_fu_1039_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln813_1_fu_1033_p2),15));

        sext_ln813_11_fu_860_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_1_fu_854_p2),14));

        sext_ln813_12_fu_870_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_2_fu_864_p2),16));

        sext_ln813_13_fu_961_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_953_p3),13));

        sext_ln813_14_fu_971_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_9_fu_965_p2),15));

        sext_ln813_15_fu_981_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_11_fu_975_p2),15));

        sext_ln813_16_fu_991_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_10_fu_985_p2),16));

        sext_ln813_1_fu_880_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_3_fu_874_p2),14));

        sext_ln813_2_fu_890_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_4_fu_884_p2),16));

        sext_ln813_3_fu_900_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln813_fu_894_p2),14));

        sext_ln813_4_fu_910_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_5_fu_904_p2),15));

        sext_ln813_5_fu_920_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_6_fu_914_p2),14));

        sext_ln813_6_fu_930_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_8_fu_924_p2),15));

        sext_ln813_7_fu_850_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_842_p3),13));

        sext_ln813_8_fu_1007_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_14_fu_1001_p2),14));

        sext_ln813_9_fu_1017_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_13_fu_1011_p2),16));

        sext_ln813_fu_816_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln841_13_fu_810_p2),15));

        sext_ln841_10_fu_585_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_fu_574_p3),12));

        sext_ln841_11_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_5_fu_595_p3),12));

    sext_ln841_12_fu_471_p0 <= p_read2;
        sext_ln841_12_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln841_12_fu_471_p0),14));

        sext_ln841_13_fu_623_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_6_fu_616_p3),14));

        sext_ln841_14_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_7_fu_627_p3),14));

        sext_ln841_15_fu_651_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_8_fu_644_p3),13));

        sext_ln841_16_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_9_fu_655_p3),13));

        sext_ln841_17_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln841_7_fu_666_p2),14));

        sext_ln841_18_fu_683_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_s_fu_676_p3),13));

        sext_ln841_19_fu_694_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_4_fu_687_p3),14));

        sext_ln841_1_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_1_fu_487_p3),13));

        sext_ln841_20_fu_698_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_4_fu_687_p3),13));

        sext_ln841_21_fu_708_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln841_8_fu_702_p2),14));

        sext_ln841_22_fu_725_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_10_fu_718_p3),13));

        sext_ln841_23_fu_735_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln841_10_fu_729_p2),14));

        sext_ln841_24_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_11_fu_739_p3),14));

        sext_ln841_25_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_12_fu_750_p3),14));

        sext_ln841_26_fu_774_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_13_fu_767_p3),13));

        sext_ln841_27_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_14_fu_778_p3),13));

        sext_ln841_28_fu_795_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln841_12_fu_789_p2),14));

        sext_ln841_29_fu_806_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_15_fu_799_p3),13));

        sext_ln841_2_fu_498_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_1_fu_487_p3),12));

        sext_ln841_3_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln841_fu_502_p2),13));

        sext_ln841_4_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_2_fu_512_p3),13));

        sext_ln841_5_fu_529_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln841_fu_523_p2),14));

        sext_ln841_6_fu_545_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln841_2_fu_539_p2),14));

        sext_ln841_8_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln841_3_fu_563_p3),13));

        sext_ln841_9_fu_581_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_fu_574_p3),14));

        sext_ln841_fu_483_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_476_p3),12));

    shl_ln841_10_fu_718_p3 <= (p_read_15_reg_1102 & ap_const_lv2_0);
    shl_ln841_11_fu_739_p3 <= (p_read_15_reg_1102 & ap_const_lv5_0);
    shl_ln841_12_fu_750_p3 <= (p_read_15_reg_1102 & ap_const_lv3_0);
    shl_ln841_13_fu_767_p3 <= (p_read_14_reg_1095 & ap_const_lv4_0);
    shl_ln841_14_fu_778_p3 <= (p_read_14_reg_1095 & ap_const_lv2_0);
    shl_ln841_15_fu_799_p3 <= (p_read_14_reg_1095 & ap_const_lv1_0);
    shl_ln841_1_fu_487_p3 <= (p_read13_reg_1129 & ap_const_lv1_0);
    shl_ln841_2_fu_512_p3 <= (p_read13_reg_1129 & ap_const_lv4_0);
    shl_ln841_3_fu_563_p3 <= (p_read114_reg_1121 & ap_const_lv2_0);
    shl_ln841_4_fu_687_p3 <= (p_read_15_reg_1102 & ap_const_lv1_0);
    shl_ln841_5_fu_595_p3 <= (p_read114_reg_1121 & ap_const_lv1_0);
    shl_ln841_6_fu_616_p3 <= (p_read215_reg_1112 & ap_const_lv5_0);
    shl_ln841_7_fu_627_p3 <= (p_read215_reg_1112 & ap_const_lv3_0);
    shl_ln841_8_fu_644_p3 <= (p_read215_reg_1112 & ap_const_lv4_0);
    shl_ln841_9_fu_655_p3 <= (p_read215_reg_1112 & ap_const_lv2_0);
    shl_ln841_s_fu_676_p3 <= (p_read_15_reg_1102 & ap_const_lv4_0);
    shl_ln_fu_476_p3 <= (p_read13_reg_1129 & ap_const_lv3_0);
    sub_ln813_1_fu_1033_p2 <= std_logic_vector(unsigned(add_ln813_15_fu_1027_p2) - unsigned(sext_ln841_19_fu_694_p1));
    sub_ln813_fu_894_p2 <= std_logic_vector(signed(add_ln841_fu_523_p2) - signed(sext_ln841_8_fu_570_p1));
    sub_ln841_10_fu_729_p2 <= std_logic_vector(unsigned(sub_ln841_9_fu_712_p2) - unsigned(sext_ln841_22_fu_725_p1));
    sub_ln841_11_fu_761_p2 <= std_logic_vector(signed(sext_ln841_24_fu_746_p1) - signed(sext_ln841_25_fu_757_p1));
    sub_ln841_12_fu_789_p2 <= std_logic_vector(signed(sext_ln841_27_fu_785_p1) - signed(sext_ln841_26_fu_774_p1));
    sub_ln841_13_fu_810_p2 <= std_logic_vector(signed(sext_ln841_26_fu_774_p1) - signed(sext_ln841_27_fu_785_p1));
    sub_ln841_1_fu_533_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(sext_ln841_4_fu_519_p1));
    sub_ln841_2_fu_539_p2 <= std_logic_vector(unsigned(sub_ln841_1_fu_533_p2) - unsigned(sext_ln841_1_fu_494_p1));
    sub_ln841_3_fu_549_p2 <= std_logic_vector(signed(sext_ln841_1_fu_494_p1) - signed(sext_ln841_4_fu_519_p1));
    sub_ln841_4_fu_589_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(sext_ln841_10_fu_585_p1));
    sub_ln841_5_fu_606_p2 <= std_logic_vector(unsigned(sub_ln841_4_fu_589_p2) - unsigned(sext_ln841_11_fu_602_p1));
    sub_ln841_6_fu_638_p2 <= std_logic_vector(signed(sext_ln841_13_fu_623_p1) - signed(sext_ln841_14_fu_634_p1));
    sub_ln841_7_fu_666_p2 <= std_logic_vector(signed(sext_ln841_15_fu_651_p1) - signed(sext_ln841_16_fu_662_p1));
    sub_ln841_8_fu_702_p2 <= std_logic_vector(signed(sext_ln841_18_fu_683_p1) - signed(sext_ln841_20_fu_698_p1));
    sub_ln841_9_fu_712_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(sext_ln841_18_fu_683_p1));
    sub_ln841_fu_502_p2 <= std_logic_vector(signed(sext_ln841_2_fu_498_p1) - signed(sext_ln841_fu_483_p1));
    tmp14_fu_836_p2 <= std_logic_vector(signed(p_read3_cast26_fu_833_p1) + signed(p_read2_cast27_fu_830_p1));
    tmp5212_fu_947_p2 <= std_logic_vector(signed(p_read2_cast27_fu_830_p1) - signed(p_read_cast29_fu_944_p1));
    tmp_4_fu_953_p3 <= (tmp5212_fu_947_p2 & ap_const_lv2_0);
    tmp_fu_842_p3 <= (tmp14_fu_836_p2 & ap_const_lv1_0);
end behav;
