-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference_linear_ap_fixed_16_6_5_3_0_ap_fixed_16_7_4_0_0_linear_config7_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of inference_linear_ap_fixed_16_6_5_3_0_ap_fixed_16_7_4_0_0_linear_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal p_Val2_s_fu_104_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_fu_118_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_6_fu_100_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_fu_132_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_fu_114_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_1_fu_142_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_1_fu_156_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_5_fu_96_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_1_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_1_fu_170_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_1_fu_152_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_2_fu_180_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_2_fu_194_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_4_fu_92_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_2_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_2_fu_208_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_2_fu_190_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_3_fu_218_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_3_fu_232_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_3_fu_88_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_3_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_3_fu_246_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_3_fu_228_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_4_fu_256_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_4_fu_270_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_2_fu_84_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_4_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_4_fu_284_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_4_fu_266_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_5_fu_294_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_5_fu_308_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_1_fu_80_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_5_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_5_fu_322_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_5_fu_304_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_6_fu_332_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_6_fu_346_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln29_fu_76_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_6_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_6_fu_360_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_6_fu_342_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_fu_136_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_1_fu_174_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_2_fu_212_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_3_fu_250_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_4_fu_288_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_5_fu_326_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln377_6_fu_364_p2 : STD_LOGIC_VECTOR (15 downto 0);


begin



    add_ln377_1_fu_174_p2 <= std_logic_vector(unsigned(zext_ln377_1_fu_170_p1) + unsigned(sext_ln818_1_fu_152_p1));
    add_ln377_2_fu_212_p2 <= std_logic_vector(unsigned(zext_ln377_2_fu_208_p1) + unsigned(sext_ln818_2_fu_190_p1));
    add_ln377_3_fu_250_p2 <= std_logic_vector(unsigned(zext_ln377_3_fu_246_p1) + unsigned(sext_ln818_3_fu_228_p1));
    add_ln377_4_fu_288_p2 <= std_logic_vector(unsigned(zext_ln377_4_fu_284_p1) + unsigned(sext_ln818_4_fu_266_p1));
    add_ln377_5_fu_326_p2 <= std_logic_vector(unsigned(zext_ln377_5_fu_322_p1) + unsigned(sext_ln818_5_fu_304_p1));
    add_ln377_6_fu_364_p2 <= std_logic_vector(unsigned(zext_ln377_6_fu_360_p1) + unsigned(sext_ln818_6_fu_342_p1));
    add_ln377_fu_136_p2 <= std_logic_vector(unsigned(zext_ln377_fu_132_p1) + unsigned(sext_ln818_fu_114_p1));
    and_ln374_1_fu_164_p2 <= (trunc_ln29_5_fu_96_p1 and tmp_1_fu_156_p3);
    and_ln374_2_fu_202_p2 <= (trunc_ln29_4_fu_92_p1 and tmp_2_fu_194_p3);
    and_ln374_3_fu_240_p2 <= (trunc_ln29_3_fu_88_p1 and tmp_3_fu_232_p3);
    and_ln374_4_fu_278_p2 <= (trunc_ln29_2_fu_84_p1 and tmp_4_fu_270_p3);
    and_ln374_5_fu_316_p2 <= (trunc_ln29_1_fu_80_p1 and tmp_5_fu_308_p3);
    and_ln374_6_fu_354_p2 <= (trunc_ln29_fu_76_p1 and tmp_6_fu_346_p3);
    and_ln374_fu_126_p2 <= (trunc_ln29_6_fu_100_p1 and tmp_fu_118_p3);
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln377_fu_136_p2;
    ap_return_1 <= add_ln377_1_fu_174_p2;
    ap_return_2 <= add_ln377_2_fu_212_p2;
    ap_return_3 <= add_ln377_3_fu_250_p2;
    ap_return_4 <= add_ln377_4_fu_288_p2;
    ap_return_5 <= add_ln377_5_fu_326_p2;
    ap_return_6 <= add_ln377_6_fu_364_p2;
    p_Val2_1_fu_142_p4 <= p_read1(15 downto 1);
    p_Val2_2_fu_180_p4 <= p_read2(15 downto 1);
    p_Val2_3_fu_218_p4 <= p_read3(15 downto 1);
    p_Val2_4_fu_256_p4 <= p_read4(15 downto 1);
    p_Val2_5_fu_294_p4 <= p_read5(15 downto 1);
    p_Val2_6_fu_332_p4 <= p_read6(15 downto 1);
    p_Val2_s_fu_104_p4 <= p_read(15 downto 1);
        sext_ln818_1_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_1_fu_142_p4),16));

        sext_ln818_2_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_2_fu_180_p4),16));

        sext_ln818_3_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_3_fu_218_p4),16));

        sext_ln818_4_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_4_fu_256_p4),16));

        sext_ln818_5_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_5_fu_294_p4),16));

        sext_ln818_6_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_6_fu_332_p4),16));

        sext_ln818_fu_114_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_s_fu_104_p4),16));

    tmp_1_fu_156_p3 <= p_read1(1 downto 1);
    tmp_2_fu_194_p3 <= p_read2(1 downto 1);
    tmp_3_fu_232_p3 <= p_read3(1 downto 1);
    tmp_4_fu_270_p3 <= p_read4(1 downto 1);
    tmp_5_fu_308_p3 <= p_read5(1 downto 1);
    tmp_6_fu_346_p3 <= p_read6(1 downto 1);
    tmp_fu_118_p3 <= p_read(1 downto 1);
    trunc_ln29_1_fu_80_p1 <= p_read5(1 - 1 downto 0);
    trunc_ln29_2_fu_84_p1 <= p_read4(1 - 1 downto 0);
    trunc_ln29_3_fu_88_p1 <= p_read3(1 - 1 downto 0);
    trunc_ln29_4_fu_92_p1 <= p_read2(1 - 1 downto 0);
    trunc_ln29_5_fu_96_p1 <= p_read1(1 - 1 downto 0);
    trunc_ln29_6_fu_100_p1 <= p_read(1 - 1 downto 0);
    trunc_ln29_fu_76_p1 <= p_read6(1 - 1 downto 0);
    zext_ln377_1_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_1_fu_164_p2),16));
    zext_ln377_2_fu_208_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_2_fu_202_p2),16));
    zext_ln377_3_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_3_fu_240_p2),16));
    zext_ln377_4_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_4_fu_278_p2),16));
    zext_ln377_5_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_5_fu_316_p2),16));
    zext_ln377_6_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_6_fu_354_p2),16));
    zext_ln377_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln374_fu_126_p2),16));
end behav;
