# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.srcs/sources_1/bd/MLZedboard/ip/MLZedboard_rst_ps7_0_100M_0/MLZedboard_rst_ps7_0_100M_0.xci
# IP: The module: 'MLZedboard_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.gen/sources_1/bd/MLZedboard/ip/MLZedboard_rst_ps7_0_100M_0/MLZedboard_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLZedboard_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.gen/sources_1/bd/MLZedboard/ip/MLZedboard_rst_ps7_0_100M_0/MLZedboard_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLZedboard_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.gen/sources_1/bd/MLZedboard/ip/MLZedboard_rst_ps7_0_100M_0/MLZedboard_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLZedboard_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.srcs/sources_1/bd/MLZedboard/ip/MLZedboard_rst_ps7_0_100M_0/MLZedboard_rst_ps7_0_100M_0.xci
# IP: The module: 'MLZedboard_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.gen/sources_1/bd/MLZedboard/ip/MLZedboard_rst_ps7_0_100M_0/MLZedboard_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLZedboard_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.gen/sources_1/bd/MLZedboard/ip/MLZedboard_rst_ps7_0_100M_0/MLZedboard_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLZedboard_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/student/Documents/laburar_aca/labs/lab08/01-Baremetal/Lab08-01/Lab08-01.gen/sources_1/bd/MLZedboard/ip/MLZedboard_rst_ps7_0_100M_0/MLZedboard_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLZedboard_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
