// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config8_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);


input   ap_clk;
input   ap_rst;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;

reg  signed [15:0] p_read512_reg_1484;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] p_read411_reg_1489;
reg  signed [15:0] p_read310_reg_1497;
reg  signed [15:0] p_read29_reg_1504;
reg  signed [15:0] p_read18_reg_1512;
reg  signed [15:0] p_read_16_reg_1520;
reg   [15:0] trunc_ln818_21_reg_1529;
reg   [13:0] trunc_ln818_25_reg_1534;
wire   [15:0] add_ln813_23_fu_887_p2;
reg   [15:0] add_ln813_23_reg_1539;
wire   [15:0] add_ln813_28_fu_893_p2;
reg   [15:0] add_ln813_28_reg_1544;
wire   [15:0] add_ln813_34_fu_905_p2;
reg   [15:0] add_ln813_34_reg_1549;
wire   [15:0] add_ln813_44_fu_917_p2;
reg   [15:0] add_ln813_44_reg_1554;
wire  signed [15:0] mul_ln1270_fu_149_p0;
wire  signed [18:0] sext_ln1270_fu_923_p1;
wire   [4:0] mul_ln1270_fu_149_p1;
wire    ap_block_pp0_stage0;
wire  signed [15:0] mul_ln1270_1_fu_152_p0;
wire  signed [18:0] sext_ln1270_1_fu_1050_p1;
wire  signed [4:0] mul_ln1270_1_fu_152_p1;
wire  signed [15:0] trunc_ln818_8_fu_631_p1;
wire   [13:0] trunc_ln818_8_fu_631_p4;
wire  signed [15:0] trunc_ln818_s_fu_645_p1;
wire   [14:0] trunc_ln818_s_fu_645_p4;
wire  signed [15:0] sext_ln1273_10_fu_659_p0;
wire  signed [15:0] shl_ln1273_7_fu_663_p1;
wire   [17:0] shl_ln1273_7_fu_663_p3;
wire  signed [18:0] sext_ln1273_11_fu_671_p1;
wire   [18:0] r_V_17_fu_675_p2;
wire  signed [18:0] sext_ln1273_10_fu_659_p1;
wire   [18:0] r_V_14_fu_681_p2;
wire  signed [15:0] shl_ln1273_10_fu_697_p1;
wire  signed [16:0] shl_ln1273_10_fu_697_p3;
wire  signed [17:0] sext_ln1273_13_fu_709_p1;
wire   [17:0] r_V_15_fu_713_p2;
wire   [14:0] trunc_ln818_19_fu_719_p4;
wire   [18:0] r_V_16_fu_733_p2;
wire  signed [15:0] shl_ln1273_11_fu_759_p1;
wire   [18:0] shl_ln1273_11_fu_759_p3;
wire   [18:0] sub_ln1273_15_fu_767_p2;
wire  signed [18:0] sext_ln1273_12_fu_705_p1;
wire   [18:0] r_V_18_fu_773_p2;
wire  signed [15:0] sext_ln1273_14_fu_789_p0;
wire  signed [15:0] shl_ln1273_12_fu_793_p1;
wire   [17:0] shl_ln1273_12_fu_793_p3;
wire  signed [18:0] sext_ln1273_15_fu_801_p1;
wire  signed [18:0] sext_ln1273_14_fu_789_p1;
wire   [18:0] r_V_19_fu_805_p2;
wire  signed [15:0] shl_ln1273_13_fu_821_p1;
wire   [18:0] shl_ln1273_13_fu_821_p3;
wire   [18:0] sub_ln1273_17_fu_829_p2;
wire   [18:0] r_V_20_fu_835_p2;
wire  signed [15:0] trunc_ln818_25_fu_851_p1;
wire  signed [15:0] trunc_ln818_26_fu_861_p1;
wire   [14:0] trunc_ln818_26_fu_861_p4;
wire   [15:0] trunc_ln818_18_fu_687_p4;
wire   [15:0] trunc_ln818_23_fu_811_p4;
wire  signed [15:0] sext_ln818_2_fu_655_p1;
wire  signed [15:0] sext_ln818_fu_641_p1;
wire   [15:0] add_ln813_22_fu_881_p2;
wire   [15:0] add_ln813_21_fu_875_p2;
wire  signed [15:0] sext_ln818_13_fu_729_p1;
wire   [15:0] trunc_ln818_24_fu_841_p4;
wire   [15:0] add_ln813_33_fu_899_p2;
wire   [15:0] trunc_ln818_20_fu_739_p4;
wire  signed [15:0] sext_ln818_5_fu_871_p1;
wire   [15:0] add_ln813_43_fu_911_p2;
wire   [15:0] trunc_ln818_22_fu_779_p4;
wire   [17:0] shl_ln_fu_927_p3;
wire  signed [18:0] sext_ln1273_fu_934_p1;
wire   [18:0] r_V_fu_938_p2;
wire   [18:0] shl_ln1273_1_fu_954_p3;
wire   [18:0] sub_ln1273_fu_961_p2;
wire   [18:0] r_V_1_fu_967_p2;
wire   [16:0] shl_ln1273_2_fu_983_p3;
wire  signed [18:0] sext_ln1273_1_fu_990_p1;
wire   [18:0] r_V_2_fu_994_p2;
wire   [18:0] mul_ln1270_fu_149_p2;
wire   [17:0] shl_ln1273_3_fu_1023_p3;
wire  signed [18:0] sext_ln1273_2_fu_1030_p1;
wire  signed [18:0] sext_ln818_12_fu_1020_p1;
wire   [18:0] r_V_3_fu_1034_p2;
wire   [16:0] shl_ln1273_5_fu_1061_p3;
wire   [18:0] shl_ln1273_4_fu_1054_p3;
wire   [18:0] sub_ln1273_3_fu_1072_p2;
wire  signed [18:0] sext_ln1273_3_fu_1068_p1;
wire   [18:0] r_V_4_fu_1078_p2;
wire   [17:0] shl_ln1273_6_fu_1094_p3;
wire  signed [18:0] sext_ln1273_4_fu_1101_p1;
wire   [18:0] r_V_5_fu_1105_p2;
wire   [18:0] mul_ln1270_1_fu_152_p2;
wire  signed [18:0] sext_ln1273_5_fu_1131_p1;
wire   [18:0] p_shl3_fu_1134_p3;
wire   [18:0] sub_ln1270_fu_1141_p2;
wire   [18:0] r_V_6_fu_1157_p2;
wire   [17:0] tmp_fu_1173_p3;
wire  signed [18:0] sext_ln1273_6_fu_1180_p1;
wire   [18:0] r_V_7_fu_1184_p2;
wire   [18:0] r_V_8_fu_1200_p2;
wire   [18:0] shl_ln1273_8_fu_1219_p3;
wire   [18:0] r_V_9_fu_1226_p2;
wire   [17:0] shl_ln1273_9_fu_1242_p3;
wire  signed [18:0] sext_ln1273_8_fu_1249_p1;
wire  signed [18:0] sext_ln1273_7_fu_1216_p1;
wire   [18:0] r_V_10_fu_1253_p2;
wire   [16:0] shl_ln1273_s_fu_1269_p3;
wire  signed [18:0] sext_ln1273_9_fu_1276_p1;
wire   [18:0] r_V_11_fu_1280_p2;
wire   [18:0] r_V_12_fu_1296_p2;
wire   [18:0] r_V_13_fu_1312_p2;
wire   [15:0] trunc_ln818_17_fu_1318_p4;
wire   [15:0] add_ln813_fu_1331_p2;
wire   [15:0] trunc_ln818_9_fu_1040_p4;
wire   [15:0] trunc_ln818_4_fu_1147_p4;
wire   [15:0] trunc_ln818_13_fu_1232_p4;
wire   [15:0] add_ln813_19_fu_1342_p2;
wire   [15:0] trunc_ln_fu_944_p4;
wire   [15:0] add_ln813_20_fu_1348_p2;
wire   [15:0] trunc_ln818_1_fu_1084_p4;
wire   [15:0] add_ln813_25_fu_1359_p2;
wire   [15:0] trunc_ln818_10_fu_1163_p4;
wire   [15:0] trunc_ln818_14_fu_1259_p4;
wire   [15:0] add_ln813_27_fu_1369_p2;
wire   [15:0] add_ln813_29_fu_1375_p2;
wire   [15:0] add_ln813_26_fu_1364_p2;
wire   [15:0] trunc_ln818_2_fu_1111_p4;
wire   [15:0] trunc_ln818_15_fu_1286_p4;
wire   [15:0] add_ln813_31_fu_1386_p2;
wire   [15:0] trunc_ln818_5_fu_973_p4;
wire   [15:0] add_ln813_32_fu_1392_p2;
wire   [15:0] trunc_ln818_6_fu_1000_p4;
wire   [15:0] trunc_ln818_11_fu_1190_p4;
wire   [15:0] add_ln813_36_fu_1403_p2;
wire   [15:0] trunc_ln818_3_fu_1121_p4;
wire  signed [15:0] sext_ln818_4_fu_1328_p1;
wire   [15:0] add_ln813_38_fu_1415_p2;
wire   [15:0] trunc_ln818_16_fu_1302_p4;
wire   [15:0] add_ln813_39_fu_1420_p2;
wire   [15:0] add_ln813_37_fu_1409_p2;
wire   [15:0] trunc_ln818_12_fu_1206_p4;
wire   [15:0] add_ln813_41_fu_1432_p2;
wire   [15:0] trunc_ln818_7_fu_1010_p4;
wire   [15:0] add_ln813_42_fu_1437_p2;
wire   [15:0] add_ln813_24_fu_1354_p2;
wire   [15:0] add_ln813_30_fu_1380_p2;
wire   [15:0] add_ln813_35_fu_1398_p2;
wire   [15:0] add_ln813_40_fu_1426_p2;
wire   [15:0] add_ln813_45_fu_1443_p2;
wire   [15:0] add_ln813_18_fu_1336_p2;
wire    ap_ce_reg;

inference_mul_16s_5ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 19 ))
mul_16s_5ns_19_1_1_U784(
    .din0(mul_ln1270_fu_149_p0),
    .din1(mul_ln1270_fu_149_p1),
    .dout(mul_ln1270_fu_149_p2)
);

inference_mul_16s_5s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 19 ))
mul_16s_5s_19_1_1_U785(
    .din0(mul_ln1270_1_fu_152_p0),
    .din1(mul_ln1270_1_fu_152_p1),
    .dout(mul_ln1270_1_fu_152_p2)
);

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln813_23_reg_1539 <= add_ln813_23_fu_887_p2;
        add_ln813_28_reg_1544 <= add_ln813_28_fu_893_p2;
        add_ln813_34_reg_1549 <= add_ln813_34_fu_905_p2;
        add_ln813_44_reg_1554 <= add_ln813_44_fu_917_p2;
        p_read18_reg_1512 <= p_read1;
        p_read29_reg_1504 <= p_read2;
        p_read310_reg_1497 <= p_read3;
        p_read411_reg_1489 <= p_read4;
        p_read512_reg_1484 <= p_read5;
        p_read_16_reg_1520 <= p_read;
        trunc_ln818_21_reg_1529 <= {{r_V_17_fu_675_p2[18:3]}};
        trunc_ln818_25_reg_1534 <= {{trunc_ln818_25_fu_851_p1[15:2]}};
    end
end

assign add_ln813_18_fu_1336_p2 = (add_ln813_fu_1331_p2 + trunc_ln818_9_fu_1040_p4);

assign add_ln813_19_fu_1342_p2 = (trunc_ln818_4_fu_1147_p4 + trunc_ln818_13_fu_1232_p4);

assign add_ln813_20_fu_1348_p2 = (add_ln813_19_fu_1342_p2 + trunc_ln_fu_944_p4);

assign add_ln813_21_fu_875_p2 = (trunc_ln818_18_fu_687_p4 + trunc_ln818_23_fu_811_p4);

assign add_ln813_22_fu_881_p2 = ($signed(sext_ln818_2_fu_655_p1) + $signed(sext_ln818_fu_641_p1));

assign add_ln813_23_fu_887_p2 = (add_ln813_22_fu_881_p2 + add_ln813_21_fu_875_p2);

assign add_ln813_24_fu_1354_p2 = (add_ln813_23_reg_1539 + add_ln813_20_fu_1348_p2);

assign add_ln813_25_fu_1359_p2 = ($signed(trunc_ln818_1_fu_1084_p4) + $signed(p_read_16_reg_1520));

assign add_ln813_26_fu_1364_p2 = ($signed(add_ln813_25_fu_1359_p2) + $signed(p_read18_reg_1512));

assign add_ln813_27_fu_1369_p2 = (trunc_ln818_10_fu_1163_p4 + trunc_ln818_14_fu_1259_p4);

assign add_ln813_28_fu_893_p2 = ($signed(sext_ln818_13_fu_729_p1) + $signed(trunc_ln818_24_fu_841_p4));

assign add_ln813_29_fu_1375_p2 = (add_ln813_28_reg_1544 + add_ln813_27_fu_1369_p2);

assign add_ln813_30_fu_1380_p2 = (add_ln813_29_fu_1375_p2 + add_ln813_26_fu_1364_p2);

assign add_ln813_31_fu_1386_p2 = (trunc_ln818_2_fu_1111_p4 + trunc_ln818_15_fu_1286_p4);

assign add_ln813_32_fu_1392_p2 = (add_ln813_31_fu_1386_p2 + trunc_ln818_5_fu_973_p4);

assign add_ln813_33_fu_899_p2 = ($signed(trunc_ln818_23_fu_811_p4) + $signed(sext_ln818_fu_641_p1));

assign add_ln813_34_fu_905_p2 = (add_ln813_33_fu_899_p2 + trunc_ln818_20_fu_739_p4);

assign add_ln813_35_fu_1398_p2 = (add_ln813_34_reg_1549 + add_ln813_32_fu_1392_p2);

assign add_ln813_36_fu_1403_p2 = (trunc_ln818_6_fu_1000_p4 + trunc_ln818_11_fu_1190_p4);

assign add_ln813_37_fu_1409_p2 = (add_ln813_36_fu_1403_p2 + trunc_ln818_3_fu_1121_p4);

assign add_ln813_38_fu_1415_p2 = ($signed(trunc_ln818_21_reg_1529) + $signed(sext_ln818_4_fu_1328_p1));

assign add_ln813_39_fu_1420_p2 = (add_ln813_38_fu_1415_p2 + trunc_ln818_16_fu_1302_p4);

assign add_ln813_40_fu_1426_p2 = (add_ln813_39_fu_1420_p2 + add_ln813_37_fu_1409_p2);

assign add_ln813_41_fu_1432_p2 = ($signed(trunc_ln818_12_fu_1206_p4) + $signed(p_read18_reg_1512));

assign add_ln813_42_fu_1437_p2 = (add_ln813_41_fu_1432_p2 + trunc_ln818_7_fu_1010_p4);

assign add_ln813_43_fu_911_p2 = ($signed(sext_ln818_2_fu_655_p1) + $signed(sext_ln818_5_fu_871_p1));

assign add_ln813_44_fu_917_p2 = (add_ln813_43_fu_911_p2 + trunc_ln818_22_fu_779_p4);

assign add_ln813_45_fu_1443_p2 = (add_ln813_44_reg_1554 + add_ln813_42_fu_1437_p2);

assign add_ln813_fu_1331_p2 = ($signed(trunc_ln818_17_fu_1318_p4) + $signed(p_read512_reg_1484));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_return_0 = add_ln813_24_fu_1354_p2;

assign ap_return_1 = add_ln813_30_fu_1380_p2;

assign ap_return_2 = add_ln813_35_fu_1398_p2;

assign ap_return_3 = add_ln813_40_fu_1426_p2;

assign ap_return_4 = add_ln813_45_fu_1443_p2;

assign ap_return_5 = add_ln813_18_fu_1336_p2;

assign mul_ln1270_1_fu_152_p0 = sext_ln1270_1_fu_1050_p1;

assign mul_ln1270_1_fu_152_p1 = 19'd524277;

assign mul_ln1270_fu_149_p0 = sext_ln1270_fu_923_p1;

assign mul_ln1270_fu_149_p1 = 19'd11;

assign p_shl3_fu_1134_p3 = {{p_read310_reg_1497}, {3'd0}};

assign r_V_10_fu_1253_p2 = ($signed(sext_ln1273_8_fu_1249_p1) - $signed(sext_ln1273_7_fu_1216_p1));

assign r_V_11_fu_1280_p2 = ($signed(sext_ln1273_9_fu_1276_p1) - $signed(shl_ln1273_8_fu_1219_p3));

assign r_V_12_fu_1296_p2 = ($signed(sext_ln1273_7_fu_1216_p1) - $signed(sext_ln1273_8_fu_1249_p1));

assign r_V_13_fu_1312_p2 = ($signed(r_V_9_fu_1226_p2) - $signed(sext_ln1273_7_fu_1216_p1));

assign r_V_14_fu_681_p2 = ($signed(r_V_17_fu_675_p2) - $signed(sext_ln1273_10_fu_659_p1));

assign r_V_15_fu_713_p2 = ($signed(18'd0) - $signed(sext_ln1273_13_fu_709_p1));

assign r_V_16_fu_733_p2 = ($signed(sext_ln1273_11_fu_671_p1) - $signed(sext_ln1273_10_fu_659_p1));

assign r_V_17_fu_675_p2 = ($signed(19'd0) - $signed(sext_ln1273_11_fu_671_p1));

assign r_V_18_fu_773_p2 = ($signed(sub_ln1273_15_fu_767_p2) - $signed(sext_ln1273_12_fu_705_p1));

assign r_V_19_fu_805_p2 = ($signed(sext_ln1273_15_fu_801_p1) + $signed(sext_ln1273_14_fu_789_p1));

assign r_V_1_fu_967_p2 = ($signed(sub_ln1273_fu_961_p2) - $signed(sext_ln1270_fu_923_p1));

assign r_V_20_fu_835_p2 = ($signed(sub_ln1273_17_fu_829_p2) - $signed(sext_ln1273_14_fu_789_p1));

assign r_V_2_fu_994_p2 = ($signed(shl_ln1273_1_fu_954_p3) + $signed(sext_ln1273_1_fu_990_p1));

assign r_V_3_fu_1034_p2 = ($signed(sext_ln1273_2_fu_1030_p1) - $signed(sext_ln818_12_fu_1020_p1));

assign r_V_4_fu_1078_p2 = ($signed(sub_ln1273_3_fu_1072_p2) - $signed(sext_ln1273_3_fu_1068_p1));

assign r_V_5_fu_1105_p2 = ($signed(sext_ln1273_4_fu_1101_p1) - $signed(sext_ln1270_1_fu_1050_p1));

assign r_V_6_fu_1157_p2 = ($signed(p_shl3_fu_1134_p3) + $signed(sext_ln1273_5_fu_1131_p1));

assign r_V_7_fu_1184_p2 = ($signed(sext_ln1273_5_fu_1131_p1) - $signed(sext_ln1273_6_fu_1180_p1));

assign r_V_8_fu_1200_p2 = ($signed(p_shl3_fu_1134_p3) - $signed(sext_ln1273_5_fu_1131_p1));

assign r_V_9_fu_1226_p2 = (19'd0 - shl_ln1273_8_fu_1219_p3);

assign r_V_fu_938_p2 = ($signed(sext_ln1273_fu_934_p1) + $signed(sext_ln1270_fu_923_p1));

assign sext_ln1270_1_fu_1050_p1 = p_read29_reg_1504;

assign sext_ln1270_fu_923_p1 = p_read_16_reg_1520;

assign sext_ln1273_10_fu_659_p0 = p_read5;

assign sext_ln1273_10_fu_659_p1 = sext_ln1273_10_fu_659_p0;

assign sext_ln1273_11_fu_671_p1 = $signed(shl_ln1273_7_fu_663_p3);

assign sext_ln1273_12_fu_705_p1 = shl_ln1273_10_fu_697_p3;

assign sext_ln1273_13_fu_709_p1 = shl_ln1273_10_fu_697_p3;

assign sext_ln1273_14_fu_789_p0 = p_read6;

assign sext_ln1273_14_fu_789_p1 = sext_ln1273_14_fu_789_p0;

assign sext_ln1273_15_fu_801_p1 = $signed(shl_ln1273_12_fu_793_p3);

assign sext_ln1273_1_fu_990_p1 = $signed(shl_ln1273_2_fu_983_p3);

assign sext_ln1273_2_fu_1030_p1 = $signed(shl_ln1273_3_fu_1023_p3);

assign sext_ln1273_3_fu_1068_p1 = $signed(shl_ln1273_5_fu_1061_p3);

assign sext_ln1273_4_fu_1101_p1 = $signed(shl_ln1273_6_fu_1094_p3);

assign sext_ln1273_5_fu_1131_p1 = p_read310_reg_1497;

assign sext_ln1273_6_fu_1180_p1 = $signed(tmp_fu_1173_p3);

assign sext_ln1273_7_fu_1216_p1 = p_read411_reg_1489;

assign sext_ln1273_8_fu_1249_p1 = $signed(shl_ln1273_9_fu_1242_p3);

assign sext_ln1273_9_fu_1276_p1 = $signed(shl_ln1273_s_fu_1269_p3);

assign sext_ln1273_fu_934_p1 = $signed(shl_ln_fu_927_p3);

assign sext_ln818_12_fu_1020_p1 = p_read18_reg_1512;

assign sext_ln818_13_fu_729_p1 = $signed(trunc_ln818_19_fu_719_p4);

assign sext_ln818_2_fu_655_p1 = $signed(trunc_ln818_s_fu_645_p4);

assign sext_ln818_4_fu_1328_p1 = $signed(trunc_ln818_25_reg_1534);

assign sext_ln818_5_fu_871_p1 = $signed(trunc_ln818_26_fu_861_p4);

assign sext_ln818_fu_641_p1 = $signed(trunc_ln818_8_fu_631_p4);

assign shl_ln1273_10_fu_697_p1 = p_read5;

assign shl_ln1273_10_fu_697_p3 = {{shl_ln1273_10_fu_697_p1}, {1'd0}};

assign shl_ln1273_11_fu_759_p1 = p_read5;

assign shl_ln1273_11_fu_759_p3 = {{shl_ln1273_11_fu_759_p1}, {3'd0}};

assign shl_ln1273_12_fu_793_p1 = p_read6;

assign shl_ln1273_12_fu_793_p3 = {{shl_ln1273_12_fu_793_p1}, {2'd0}};

assign shl_ln1273_13_fu_821_p1 = p_read6;

assign shl_ln1273_13_fu_821_p3 = {{shl_ln1273_13_fu_821_p1}, {3'd0}};

assign shl_ln1273_1_fu_954_p3 = {{p_read_16_reg_1520}, {3'd0}};

assign shl_ln1273_2_fu_983_p3 = {{p_read_16_reg_1520}, {1'd0}};

assign shl_ln1273_3_fu_1023_p3 = {{p_read18_reg_1512}, {2'd0}};

assign shl_ln1273_4_fu_1054_p3 = {{p_read29_reg_1504}, {3'd0}};

assign shl_ln1273_5_fu_1061_p3 = {{p_read29_reg_1504}, {1'd0}};

assign shl_ln1273_6_fu_1094_p3 = {{p_read29_reg_1504}, {2'd0}};

assign shl_ln1273_7_fu_663_p1 = p_read5;

assign shl_ln1273_7_fu_663_p3 = {{shl_ln1273_7_fu_663_p1}, {2'd0}};

assign shl_ln1273_8_fu_1219_p3 = {{p_read411_reg_1489}, {3'd0}};

assign shl_ln1273_9_fu_1242_p3 = {{p_read411_reg_1489}, {2'd0}};

assign shl_ln1273_s_fu_1269_p3 = {{p_read411_reg_1489}, {1'd0}};

assign shl_ln_fu_927_p3 = {{p_read_16_reg_1520}, {2'd0}};

assign sub_ln1270_fu_1141_p2 = ($signed(sext_ln1273_5_fu_1131_p1) - $signed(p_shl3_fu_1134_p3));

assign sub_ln1273_15_fu_767_p2 = (19'd0 - shl_ln1273_11_fu_759_p3);

assign sub_ln1273_17_fu_829_p2 = (19'd0 - shl_ln1273_13_fu_821_p3);

assign sub_ln1273_3_fu_1072_p2 = (19'd0 - shl_ln1273_4_fu_1054_p3);

assign sub_ln1273_fu_961_p2 = (19'd0 - shl_ln1273_1_fu_954_p3);

assign tmp_fu_1173_p3 = {{p_read310_reg_1497}, {2'd0}};

assign trunc_ln818_10_fu_1163_p4 = {{r_V_6_fu_1157_p2[18:3]}};

assign trunc_ln818_11_fu_1190_p4 = {{r_V_7_fu_1184_p2[18:3]}};

assign trunc_ln818_12_fu_1206_p4 = {{r_V_8_fu_1200_p2[18:3]}};

assign trunc_ln818_13_fu_1232_p4 = {{r_V_9_fu_1226_p2[18:3]}};

assign trunc_ln818_14_fu_1259_p4 = {{r_V_10_fu_1253_p2[18:3]}};

assign trunc_ln818_15_fu_1286_p4 = {{r_V_11_fu_1280_p2[18:3]}};

assign trunc_ln818_16_fu_1302_p4 = {{r_V_12_fu_1296_p2[18:3]}};

assign trunc_ln818_17_fu_1318_p4 = {{r_V_13_fu_1312_p2[18:3]}};

assign trunc_ln818_18_fu_687_p4 = {{r_V_14_fu_681_p2[18:3]}};

assign trunc_ln818_19_fu_719_p4 = {{r_V_15_fu_713_p2[17:3]}};

assign trunc_ln818_1_fu_1084_p4 = {{r_V_4_fu_1078_p2[18:3]}};

assign trunc_ln818_20_fu_739_p4 = {{r_V_16_fu_733_p2[18:3]}};

assign trunc_ln818_22_fu_779_p4 = {{r_V_18_fu_773_p2[18:3]}};

assign trunc_ln818_23_fu_811_p4 = {{r_V_19_fu_805_p2[18:3]}};

assign trunc_ln818_24_fu_841_p4 = {{r_V_20_fu_835_p2[18:3]}};

assign trunc_ln818_25_fu_851_p1 = p_read6;

assign trunc_ln818_26_fu_861_p1 = p_read6;

assign trunc_ln818_26_fu_861_p4 = {{trunc_ln818_26_fu_861_p1[15:1]}};

assign trunc_ln818_2_fu_1111_p4 = {{r_V_5_fu_1105_p2[18:3]}};

assign trunc_ln818_3_fu_1121_p4 = {{mul_ln1270_1_fu_152_p2[18:3]}};

assign trunc_ln818_4_fu_1147_p4 = {{sub_ln1270_fu_1141_p2[18:3]}};

assign trunc_ln818_5_fu_973_p4 = {{r_V_1_fu_967_p2[18:3]}};

assign trunc_ln818_6_fu_1000_p4 = {{r_V_2_fu_994_p2[18:3]}};

assign trunc_ln818_7_fu_1010_p4 = {{mul_ln1270_fu_149_p2[18:3]}};

assign trunc_ln818_8_fu_631_p1 = p_read1;

assign trunc_ln818_8_fu_631_p4 = {{trunc_ln818_8_fu_631_p1[15:2]}};

assign trunc_ln818_9_fu_1040_p4 = {{r_V_3_fu_1034_p2[18:3]}};

assign trunc_ln818_s_fu_645_p1 = p_read2;

assign trunc_ln818_s_fu_645_p4 = {{trunc_ln818_s_fu_645_p1[15:1]}};

assign trunc_ln_fu_944_p4 = {{r_V_fu_938_p2[18:3]}};

endmodule //inference_dense_latency_ap_fixed_16_7_4_0_0_ap_fixed_16_6_5_3_0_config8_s
